### ISSUE TITLE
Does not integrate with Chrome's spell check 

### ISSUE THREAD

**Issue by huangp** [codemirror/codemirror5#1017]
### Code snippet:

``` html
<div style="width:200px" contenteditable="true" spellcheck="true">
        <textarea id="code" name="code">
        javaCode {   
            stuff   
        }   
        aaaaaaaaaaaaaa 
        <a>abc</a>;
        </textarea>
    </div>

    <script>
      var editor = CodeMirror.fromTextArea(document.getElementById("code"), 
        {
            lineNumbers: true,
            lineWrapping: true,
            mode: "htmlxml"
        });  
    </script>
    <div contenteditable="true" spellcheck="true">
        pure content editable div. asdf asdf yoh.
    </div>
```

In Firefox if browser spell check is enabled then inside the editor words are marked. In Chrome, it doesn't work (maybe not entirely. Sometimes I can trigger one word to be marked but not consistently). 
### NOTE

I also included a pure content editable div underneath. In Chrome, it won't mark spelling error at page load time. But once focusing on the word or start editing the content, spell check take into effect. So not sure if is this a Chrome thing or CodeMIrror thing.

**Comment by scottyli** [comment]
@huangp how exactly did you get it to work with ```contenteditable="true"  spellcheck="true"``` ?

These method have not worked for me:
1. Attaching to the body ```<body contenteditable="true"  spellcheck="true">```
2. Attaching it to the CodeMirror element
3. Attaching it to individual span elements within .CodeMirror ```<span contenteditable="true"  spellcheck="true">```

**Comment by eduncan911** [comment]
@scottyli See my post https://github.com/codemirror/CodeMirror/issues/1017#issuecomment-52249542.

Which, points to my JS examples over in another comment thread:

https://github.com/prose/prose/issues/169#issuecomment-51637456

**Comment by WesCossick** [comment]
For those still wondering, or for future viewers, I've created a CodeMirror plugin that spell checks as your write. It's super simple to set up. Check it out at: https://github.com/NextStepWebs/codemirror-spell-checker

**Comment by eduncan911** [comment]
:+1:

**Comment by kofifus** [comment]
I created a spellchecker with typo corrections 

[https://gist.github.com/kofifus/4b2f79cadc871a29439d919692099406](https://gist.github.com/kofifus/4b2f79cadc871a29439d919692099406)

**Comment by WesCossick** [comment]
@kofifus would you be interested in submitting a PR with this functionality to https://github.com/NextStepWebs/codemirror-spell-checker?

**Comment by kofifus** [comment]
Thx Wes, I I don't see how a PR will work as basically there is not much common code ..

**Comment by kofifus** [comment]
I have updated the gist to use an async version of typo.js, this gives much faster performance speed/memory and shows suggestions as they are found .

[gist](https://gist.github.com/kofifus/4b2f79cadc871a29439d919692099406)
[demo](https://plnkr.co/edit/0y1wCHXx3k3mZaHFOpHT)

**Comment by kofifus** [comment]
Apache

**Comment by terrylinooo** [comment]
I created a dictionary files source here: 
https://spellcheck-dictionaries.github.io/

You can use it for typo.js or other spellcheck solutions as well.

**Comment by RomainLWiz** [comment]
Has someone managed to implement one of the proposed solutions ? 
From my side I can only touch the sub folder to use the admin plugins.
If you have some tips or an example I am open.
