### ISSUE TITLE
tab to spaces

### ISSUE THREAD

**Issue by tony1223** [codemirror/codemirror5#106]
Here's a feature request for translating tab to spaces. (like one tab -> two or four spaces )

Code mirror use pre to emulate tabs , but the default tab width in browser is too big ,
A suggestion is to create a option to use spaces with a xml-tab wrapper to instead of tab.

That will make it more useful , although I think it also will gain some performance cost.

**Comment by dvkndn** [comment]
> Ah, I see what you mean now. This is not practical, unfortunately, until browsers allow reliable control over tab-size through CSS styling. To make cursor movement consistent, the tab size in the display has to match the tab size in the hidden textarea.

Just want to give an update that it's possible now with the `ch` unit. So `.cm-tab { width: 8ch }` will make the tab has the width of 8 characters
