### ISSUE TITLE
Setting editor to "nocursor" readonly mode should still allow c&p

### ISSUE THREAD

**Issue by SoftwareDreamer** [codemirror/codemirror5#1099]
As the topic title says: Setting editor to "nocursor" readonly mode should still allow copy&paste operations. 

The problem with readOnly : true is, that it implies "writability" for the normal user, as the cursor blinks, which is really confusing. But in "nocursor" mode, copying is suppressed, which is also irritating and not the xpected behavior (at least from me and 2 collegues).

It would be nice to fix that, if it's an unintentional oversight. Thanks!

edit: this is observed the behavior in FF 18 beta and newest Chrome

**Comment by dchacke** [comment]
I came here from Google wondering about the same thing. In case anyone is wondering how to apply this only to some text editors and not all, this worked for me:

```javascript
var cm = CodeMirror.fromTextArea(htmlElement, { /* options */ });

// Some condition to apply this to only text editors that are meant to be readonly
if (readonly) {
    var $wrapper = $(cm.getWrapperElement());
    $wrapper.addClass('CodeMirror-readonly'); // hides cursor
}
```

Paired with the following css:

```css
/* Hide cursor in readonly fields */
.CodeMirror-readonly .CodeMirror-cursor {
  display: none !important
}
```
