### ISSUE TITLE
Redraw of widgets

### ISSUE THREAD

**Issue by mattpass** [codemirror/codemirror5#1115]
It seems that widgets are (unnecessarily?) redrawn on typing on the associated line?

This wouldn't be such a problem for widgets containing client side resources, but will cause obvious flickering issues if the widget contains resource dependent items such as an iFrame to a file (as you type each char, the src is reloaded, due to redraws).

See here for demo:
http://icecoder.net/widget-fonc/index.php

Using v3.0 and latest Chrome.

**Comment by MasseGuillaume** [comment]
I'm using POST to an iframe display syncing remove them from the view and their content are emptied.
