### ISSUE TITLE
Make it possible to style entire blocks of lines

### ISSUE THREAD

**Issue by 0b10011** [codemirror/codemirror5#1157]
Right now, it's not possible (afaik) to style an entire line (or multiple lines) for block-level highlighting sections. For example, in [GFM mode](http://codemirror.net/mode/gfm/index.html), there's no way to add a background that extends to the edges of the editor behind the code block (to set it part from the rest of the code).

Although for many languages embedded into GFM mode, especially smaller code blocks, there isn't much confusion, when Markdown (or HTML) or a very long block of code is embedded, it can be hard to tell the difference between the code block, and the actual code.

Here's what I'd like to be able to do (notice the gray background behind the code block):

![Example document with background behind entire line.](https://f.cloud.github.com/assets/1123348/65201/754768e8-5e6e-11e2-8ff0-1718edc02344.png)
### Idea 1 (preferred)

Extend the last character's style to the edge of the editor, either by adding an empty element after the last character, or adjusting the size of the last character's wrapper accordingly. This makes it possible to have multiple levels of block-level styles. Consider the following example:

```
- foo

        bar
```

The list item could have a background that spanned the entire width of line 1 & 2. Then, for line 3, the list background would continue _to_ the word `bar`, where the background for code would start and continue to the end of the line. Personally, this would be ideal.

The only issue that comes to mind for this solution is a possible performance hit due to recalculating the width of the background every time a character is typed. One workaround for this would be an `overflow:hidden;` hack of some sort. Another workaround would be to only extend the styles to the end of the line if one of the classes listed started (or ended) with `block-`. Then, only the modes that actually used it, would have to deal with it.
### Idea 2

Make it possible to add a class to the `pre` that wraps the `span`s during the highlighting phase. Or add another block-level wrapper inside the `pre` to add the class to. This could be added as `blockToken`.

The downside of this solution is it only supports one level of block-level code. For example, a code block inside of a list would only have the list's class listed. Adding the class for each would break for code within a blockquote (`>` would be highlighted as code as well, when it shouldn't be). But, this solution could always be tweaked for each mode to make it work (better than no block-level styles at all).
## Why I believe the functionality should be built into the core highlighting code

Every mode I've dealt with has had a block-level specific function and inline-level specific function. Many times, there's been more than one for each. However, few add a background to the block-level styles because it's not easy to read (or they don't think it looks good). Additionally, this should be rather easy to integrate into modes that have already been written, without having to add much more code (for the most part, it should just be rearranging things a bit).

**Comment by shoaibsharif** [comment]
So how can I enable to add a class name in markdown code block so that I can highlight this.
