### ISSUE TITLE
Android native app using WebView, backspace doesn't work properly

### ISSUE THREAD

**Issue by glinden** [codemirror/codemirror5#1196]
This may be no surprise as mobile is only loosely supported, but I don't see an existing report for this, so let me report it.

CodeMirror does work in Chrome on Android (4.2) tablets and phones, but does not work with WebView in a native Android App.  Specifically, if you load an html file that uses CodeMirror using WebView in a native Android App, when the user tries to use the CodeMirror editor to edit text, the Android keyboard will not let you delete existing text.

This may sound like an obscure problem, but it is fairly common to want to bundle up an HTML5 website as an Android app, including the website files in the app and then using WebView to load them locally, all without using the network.  But you can't if your html uses CodeMirror, which is somewhat unfortunate.

I have a simple repro case, but it does require setting up an Android app development environment (http://developer.android.com/sdk/index.html).  Then, with the latest CodeMirror, the simplest repro is to create a Blank Activity, then change MainActivity.java to contain

```
public class MainActivity extends Activity {

    @SuppressLint("SetJavaScriptEnabled") @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        WebView myWebView = (WebView) findViewById(R.id.webview);
        myWebView.setWebViewClient(new MyWebViewClient());
        WebSettings webSettings = myWebView.getSettings();
        webSettings.setJavaScriptEnabled(true);
        webSettings.setLoadWithOverviewMode(true);
        webSettings.setUseWideViewPort(true);
        myWebView.loadUrl("file:///android_asset/test.html");
    }
}
```

Then you need to set up assets to contain your local html and js files.  Simplest html is a file test.html:

```
<html>
<head>
<script src="codemirror.js"></script>
<link rel="stylesheet" href="codemirror.css">
<script src="javascript.js"></script>
</head>
<body>
<script>
var myCodeMirror = CodeMirror(document.body, {
  value: "function myScript(){return 100;}\n",
  mode:  "javascript"
});
</script>
</body>
</html>
```

which you will need to create in assets/ or create elsewhere and import into assets/.  Then you need to import into assets at the top-level codemirror.css, codemirror.css, and javascript.js from the latest CodeMirror library.  Run it to bring up a virtual device, when the app comes up, click in the code in the CodeMirror editor, and you'll see you can't use backspace to delete the existing code in the virtual keyboard.

The problem may be related to how Android handles editing with the virtual keyboard.  In particular, the way CodeMirror sets up a div (instead of a textarea) and handles all the selection in the div might be conflicting with how Android determines whether there is any text left to backspace over (the discussion at https://github.com/mathquill/mathquill/pull/78 might be related).  Android does let you edit textareas, so the issue appears to be somewhere between CodeMirror being clever about selection in its div and some optimization Android's virtual keyboard is doing on selection that only applies to a native app using WebView, not to the Chrome browser.

Anyway, totally realize that CodeMirror isn't designed for mobile, that the problem is related to Android's implementation of WebView, and that this is extremely likely to just be marked as "closed will not fix" immediately.  But I thought you and others might want to know about the issue, so I thought I'd write about it here.

Thanks for the amazing work on this library, by the way, absolutely love it.

**Comment by jaredrummler** [comment]
I just want a confirmation: @glinden were you able to get this working with one of the answers from StackOverflow?

**Comment by glinden** [comment]
@jaredrummler I didn't try the InputConnection override of the default behavior of the virtual keyboard. That seems like a fragile solution to me, too fragile to be worthwhile for my particular application. I put effort into this more because I was interested in the root cause ("Google claims this is by design, that you should never count on the virtual keyboard actually sending key events to the application").

**Comment by merbin2012** [comment]
This is the "Android system webview" problem. Thats why after update this onle i faced many problem in my application, the application name is  HTML Code Play.
