### ISSUE TITLE
text/plain missing in modeInfo list

### ISSUE THREAD

**Issue by benbro** [codemirror/codemirror5#1267]
Can you please add text/plain to the list of modes?
{name: 'Plain Text', mime: 'text/plain', mode: 'null'}

It will be nice to order the modes in the list by mode name.

Thanks

**Comment by dhbahr** [comment]
A question on this issue, how do one specifies the 'null' mode? I get a 404 for the alleged null.js

**Comment by marijnh** [comment]
The null mode should be predefined by the core library. You can refer to it as `"null"` or `"text/plain"`.
