### ISSUE TITLE
Unexpected scroll position after setValue twice and calling scrollIntoView

### ISSUE THREAD

**Issue by JosephPecoraro** [codemirror/codemirror5#1351]
At CodeMirror: f936a70

I'm seeing an issue where if I set the value of an editor twice and call scrollIntoView I'm not getting the scroll position as I would expect it.

Reduction:

``` html
<style>.CodeMirror { height: 5em; } /* 5 lines tall */</style>
<button id="button">Change text and reveal line</button>
<textarea id="code"></textarea>

<script>
// Create editor.
var textarea = document.getElementById('code');
var cm = CodeMirror.fromTextArea(textarea, {lineNumbers: true, lineWrapping:true});
// Create 300 lines.
for (var i=0, lines=[]; i<300; ++i) lines.push(i);
// Set the lines and scroll into view line 251.
document.getElementById('button').addEventListener('click', function() {
    cm.setValue("abc");
    cm.setValue(lines.join("\n"));
    cm.setSelection({line: 250, ch:0}, {line: 250});
    cm.scrollIntoView({line: 250, ch:0});
});
</script>
```

After clicking the button twice the editor is at line 1:

![Screen Shot 2013-03-12 at 5 56 42 PM](https://f.cloud.github.com/assets/11351/251877/f03719ae-8b78-11e2-9749-10321fd36f31.png)

First time clicking the button correctly scrolls to line 251. The second time however it scrolls to line 1. It continues to alternate on future clicks between line 251 and line 1. I would always expect the result to be line 251. Note the selection is still correct even though the line is not visible.

**Comment by curran** [comment]
Related discussion thread [how to set view stay in current position when cm.doc.setValue()](https://discuss.codemirror.net/t/how-to-set-view-stay-in-current-position-when-cm-doc-setvalue/570/4).

FWIW, this is how I managed to call `setValue` and not have any scroll modifications:

```js
  // Set the value, but do not scroll to the top.
  var scrollInfo = this.codeMirror.getScrollInfo();
  this.codeMirror.setValue(value);
  this.codeMirror.scrollTo(scrollInfo.left, scrollInfo.top);
```

I wish there were an options object to `setValue`, similarly to `setSelection`, so one could say:

```js
this.codeMirror.setValue(value, {scroll: false});
```
