### ISSUE TITLE
Erroneous "blur" dispatch

### ISSUE THREAD

**Issue by crdev** [codemirror/codemirror5#1394]
In v3:
1) Drag-select some text in the editor
2) Click inside the selection

Actual:
The "blur" event is dispatched on the CodeMirror editor.

Expected:
The selection is collapsed to the mouse pointer location.

**Comment by MissChocoe** [comment]
This is an issue for me two. The order of the event is hard to predict, especially in IE since the mouse up trick doesn't work well (the event order isn't always right). So finally, I used a timeout which I don't find really elegant but does work.
