### ISSUE TITLE
Getting an already built instance

### ISSUE THREAD

**Issue by Pomax** [codemirror/codemirror5#1413]
I can't find any mention in the documentation on how to obtain a reference to a CodeMirror instance after the fact (i,e, created in an in closure). I'm writing some bookmarklets at the moment and can't find any way to hook into a page's codemirror instance. Is there a CodeMirror.getInstances() or CodeMirror.getFromTextArea() that can be used to obtain a reference for further work?

**Comment by RedaBenh** [comment]
really important to write a small  example of how to get instance of Codemirror from textArea
