### ISSUE TITLE
Question: How to integrate real lexer

### ISSUE THREAD

**Issue by fbezdeka** [codemirror/codemirror5#1594]
Hi there!

I'm writing a kind of framework, that allows you to generate lexer/scanner, parser and code highlighters from a kind of language definition / grammar file. 
(Something like Xtext, ANTLR, but writtin in JavaScript and generating JavaScript code)

The lexer generator is already available and the generated lexer/scanner is working fine.
Getting the written code out of the CodeMirror editor instance is quite easy.

After the lexer has completed, I know where all my tokens start and end. 
I have the following position information about each token:
- start position (absoulte position in the input stream)
- line number (number of line where the start of the token appeared)
- line column (where exactly inside the line the token started)

If required, it should be possible to add more position information.

There is only one (hopefully little) thing missing: Highlighting tokens.

Is there something available, that would mark token A (start at position x, with length y, and z lines involved) as a keyword, terminal symbol etc. ?

Thanks!

**Comment by dhowe** [comment]
Was also thinking about this. Seems a lot of effort is duplicated when writing CodeMirror rules and for an ANTLR grammar. Not sure how difficult this would be, but it would be nice if you could supply ANTLR lexer/parser rules with accompanying token names to CodeMirror. I guess the tradeoff would be, as you say, the performance hit of running the ANTLR code each time you need syntax highlighting.

**Comment by marijnh** [comment]
Yes, running all of ANTLR doesn't seem like a great idea. It should be possible, and not terribly hard, to write a tool that converts declarative ANTLR token syntax into a lightweight CodeMirror mode, but I don't think anyone has done that so far.

(In CodeMirror 6, I'm trying to provide a more declarative syntax definition tool with [lezer](https://github.com/lezer-parser).)

**Comment by RuslanZh** [comment]
If someone is interested in the integration of Codemirror 6 and Antlr4 grammar,
you can find an example on [github page](https://github.com/RuslanZh/codemirror-antlr4).

The main idea is here:

```
token: (stream, state) => {
        // getting tokens for the current stream.string, using antlr4 TokenStream
        const tokens = getTokensForText(stream.string);
        // getting the next token
        const nextToken = tokens.filter(t => t.startIndex >= stream.pos)[0];
        // matching the next token in current stream
        if (stream.match(nextToken.text)) {
            let valueClass = getStyleNameByTag(tags.keyword);

            switch (nextToken.type) {
                case ...:
                    valueClass = getStyleNameByTag(tags.string);
                    break;
               ...
                default: 
                    valueClass = getStyleNameByTag(tags.keyword);
                    break;
             }

            return valueClass;
        } else {
            stream.next();
            return null;
        }
    }
```
