### ISSUE TITLE
incorrect cursor position on wrapped lines for some users with Chrome

### ISSUE THREAD

**Issue by jdleesmiller** [codemirror/codemirror5#1642]
We've had several reports of the cursor not appearing in the right place on wrapped lines in Chrome (as evidenced by inserts / deletes happening elsewhere). I still can't reproduce these issues, but now one of our users has submitted screenshots illustrating it on the CodeMirror b-tree demo, which may be of some help.

Unlike #1219, the string doesn't have any non-ASCII characters. It's just:

Interpolants are logical assertions over program states that can separate program states that satisfy a desired propert from one that violate the property.\\

Unlike #1353, it only seems to affect some users -- and never me, so far.

The first screenshot shows the apparent position of the cursor, after 'y' in 'satisfy':

![picture_5](https://f.cloud.github.com/assets/160829/724795/ef8a927c-e03e-11e2-8aad-5fb073b1c901.jpg)

The second screenshot shows the result of pressing backspace:

![picture_6](https://f.cloud.github.com/assets/160829/724794/ea2f1938-e03e-11e2-8827-fca45e039cdb.jpg)

The expected result was that the 'y' would be deleted, but the 'f' before the 'y' was deleted instead.

The information I have collected from users so far:
1. This user reported the problem on Chrome stable on Windows 7. The user does not think he has any browser extensions installed. The problem does not appear in Firefox.
2. It affects both inserts and deletes. It does not matter how you position the cursor (mouse or keyboard arrows).
3. It is not always off by one -- it sometimes deletes a character several characters behind the apparent cursor position.
4. The first display line of text (before the wrap) does not have the problem.

I thought it might be related to the user's locale, but I could not reproduce the issue on a French Windows 7 (up-to-date SP1) running a French Chrome (27.0), which matches this user's setup, so that does not appear to be the case.

I'll keep trying to get more information about this from the users who report it -- I'm sorry that there's not much to go on yet, but I figured I'd report it here to see whether anyone has any ideas.

**Comment by androidadvocate** [comment]
Hi this issue is still happening and it's now 2015.

**Comment by samueleaton** [comment]
Triggering a resize event whenever I wanted the cursor to go to the correct position worked for me:  `window.dispatchEvent(new Event('resize'));`

**Comment by marijnh** [comment]
You can also call `.setSize()` (without arguments) on the editor. Note that this is only necessary if your code (or some CSS reflow not caused by a window resize) somehow changed the layout or size of the editor.

**Comment by danielo515** [comment]
I'm still suffering this issue.

I have tried with `refresh` and triggering a resize event and nothing works.

Any other solution?

**Comment by marijnh** [comment]
Submit a self-contained demo that makes it easy for me to reproduce this, and I'll look into it (mention browser version etc)

**Comment by danielo515** [comment]
I'm using it along with other libraries. Should I include them in the demo as well ?

**Comment by marijnh** [comment]
**Only** if they are necessary to cause the problem to happen.

**Comment by danielo515** [comment]
Hello @marijnh 

Let me know if this is too complex

http://tiddlywiki.com/plugins/tiddlywiki/codemirror/index.html

* On the lorem ipsum "window" click on `show preview`
* Click on the arrob at the very top right:
![image](https://cloud.githubusercontent.com/assets/2270425/10317551/421af9e6-6c65-11e5-90cd-57ffadf4fe7a.png)
* Put the cursor at the end of line one, and move it.


Regards

**Comment by marijnh** [comment]
You don't appear to be calling `refresh()` after resizing the editor. If I do so manually from the dev console, things work fine again.

**Comment by danielo515** [comment]
Hello @marijnh,

I'm not sure of the refresh() on that particular example, but I'm sure that in the other place where I'm using code-mirror I am triggering the refresh.

Let me build an example and I'll post it here.

**Comment by gonzalezi2** [comment]
I think this might be a related example but I am getting the cursor jumping as well.

Chrome  49.0.2623.112 m

Here's a video of it in action. 

https://www.youtube.com/watch?v=6VLSZdoeSQ0

**Comment by marijnh** [comment]
Does a call to `.refresh()` solve it? If so, could it be that you resized/showed the editor without notifying it at some point before the issue appears?

**Comment by peterrobinson** [comment]
I am still having what seems a related problem in 2017. You can see this at [http://www.textualcommunities.org/app/community/?id=57598982b952f25827bd401c&route=view](http://www.textualcommunities.org/app/community/?id=57598982b952f25827bd401c&route=view.)
Type fast anywhere in the text input window at lower left and the cursor leaps to the start of the text and goes on from there. Why? I have linewrap on -- turning it off does not help

**Comment by marijnh** [comment]
Your cursor is being reset to the start of document somehow. This has nothing to do with this issue. It's likely something that your code does, but if you can reproduce it in a plain CodeMirror, feel free to open another issue.

**Comment by trevorhreed** [comment]
**For anyone else who comes across this...**

Had a problem with this. I think it has to do with the way I lay everything out and the code mirror container changing sizes when I set the value. If I use the following code, it resolves the issue:

```javascript
var editor = CodeMirror.fromTextArea(...)
editor.on('change', () => {
  setTimeout(() => {
    editor.refresh()
  })
})
editor.setValue(...)
```

**Comment by apbarrero** [comment]
I can reproduce the issue in Chrome 76+, and none of the hacks above, either calling `refresh` or changing CSS for `word-break: break-word` have worked for me.

It worked fine in Chrome 74 (didn't try 75).

**Comment by davidhadas** [comment]
I encountered the same problem with Chrome 87

After trying out different solutions - the below solved it for me:
myCodeMirror.on("mousedown", function () {
                myCodeMirror.refresh()
});

the solution suggested above with setTimeout did not work....!
