### ISSUE TITLE
After tabbing into CodeMirror, text input doesn't match cursor location

### ISSUE THREAD

**Issue by peterflynn** [codemirror/codemirror5#1730]
1. Go to http://codemirror.net/demo/theme.html
2. Select anything
3. Click on the dropdown widget below CodeMirror
4. Press Tab until focus returns to CodeMirror (on Chrome this takes 4 presses)
5. Type a letter

Result:
After step 4, the selection is gone and the cursor is at where the selection _end_ had been.  But the letter you type goes to where the selection _beginning_ had been.

**Comment by Billiam** [comment]
Obviously this is an ancient issue, but it seemed like the best place to discuss it.

Is this hack still necessary, 8 years later? Is it useful for contenteditable (which wasn't added for a couple of years), or could it be limited to textinput only instead?

I'm running into trouble restoring the current selection when tabbing between multiple inputs in chrome, and tracked it down to this input reset. 

I can add a setTimeout with an even longer delay before restoring tghe selection, but that results in a slightly ugly flash of unselected content.
