### ISSUE TITLE
Cursor mispositioning when using a custom font with unicode text

### ISSUE THREAD

**Issue by Pomax** [codemirror/codemirror5#1813]
We were running into some weird behaviour on thimble.webmaker.org when using languages that require unicode with combining diacritics and custom fonts, where the cursor positions and actual text don't line up. STR are thankfully easy:
1. load up http://codemirror.net/demo/complete.html
2. open the web  console, "edit as html" one of the style elements in the head and add this to the end of it:

```
<style>
@font-face {
  font-family: ubuntu;
  src: url('https://thimble.webmaker.org/friendlycode/css/ubuntumono/ubuntumono-r.woff');
}
</style>
```
1. add a new CSS rule `* { font-family: ubuntu!important; }`

All elements on the page should now be using the Ubuntu Mono Regular font.
1. clear the codemirror area and put in this text instead:

```
ดำดำดำดำดำดำดำดำดำ
กำกำกำกำกำกำกำกำกำ
```

This is just some nonsense Thai text, but demonstrates the problem immediately: click anywhere in the text, then hit enter, and notice that line gets broken in a completely different place. Placing the cursor at the start of the line and using the right cursor key to walk through it also shows the cursor moving far more than the rendered text suggests it should.

**Comment by niftylettuce** [comment]
Same issue here
