### ISSUE TITLE
[xml mode] XML autocomplete from XSD schema

### ISSUE THREAD

**Issue by abahgat** [codemirror/codemirror5#1872]
It would help to have the possibility for CodeMirror to generate [schemaInfo objects](http://codemirror.net/doc/manual.html#addon_xml-hint) straight from an XSD file.

I am aware of a [project](http://q42jaap.github.io/xsd2codemirror/) that allows to create schema files in json, but that works offline and only on Windows.

The ideal solution would be to fetch the XSD from a URL, parse it and translate it to the corresponding schema info.
There are some things that the current hint mechanism does not seem to support yet, such as [order-dependent](http://www.w3schools.com/schema/schema_complex_indicators.asp) validations (as the ones specified with `xs:sequence`)

**Comment by bogal** [comment]
Another vote for this feature.

**Comment by limonides** [comment]
Another vote for this feature.

**Comment by marijnh** [comment]
We're not extending the scope of the core library anymore, so if you need this, the way forward is to implement it and distribute it yourself.
