### ISSUE TITLE
New Font Size not getting applied to full text in editor.

### ISSUE THREAD

**Issue by mick000** [codemirror/codemirror5#1906]
Hi,

I have a text in code mirror editor. Scroll bar is enabled since the text is more. Now, I am trying to change the font size of the text. Ideally I am using the following line to change the size of the entire text
  $(".CodeMirror pre").css('font-size',"20pt");
The font changes successfully till the display area. Now if I scroll down the editor, the font-size is not changed and if I scroll up, the earlier changes are reverted back.

This problem occurs in IE8,IE9 and firefox 24.0. Am using Windows OS. The codemirror version is 3.18

I am attaching the screenshot of the same. The order in which the image is to be viewed is step 1,step 2,step 3 and step 4.

Thanks in advance. 

Step 1 - Before on click - Initial page load

![step 1 - initial](https://f.cloud.github.com/assets/5752069/1389143/7dcfb012-3bcf-11e3-97c4-412103b26edb.JPG)

Step 2 - After clicking font size change button

![step 2 - after clicking change size](https://f.cloud.github.com/assets/5752069/1389141/7dcf6292-3bcf-11e3-9bf9-1424b8200e22.JPG)

Step 3 - Scroll Down

![step 3 - scroll down](https://f.cloud.github.com/assets/5752069/1389142/7dcf912c-3bcf-11e3-9565-7b4214b1baf1.JPG)

Step 4 - Scroll Up Again

![step 4 - scroll up](https://f.cloud.github.com/assets/5752069/1389144/7dd090fe-3bcf-11e3-8ccf-cfd245185e02.JPG)

**Comment by alvarobyrne** [comment]
```
		let codemirror_pres = document.querySelectorAll(".CodeMirror pre")
		codemirror_pres.forEach(function (argument) {
			argument.style.fontSize = font_size+'px';
			argument.style.height = (font_size+3)+'px';
		})
		}
```
