### ISSUE TITLE
Highlight a error word

### ISSUE THREAD

**Issue by ducbin** [codemirror/codemirror5#1915]
I want to highlight a word that has spelling-error. I use typo.js and make defineMode. For the link, that change the style of link but for the word that changes always the style of all words of line. I just want to change style of the error word. Can you help me ?

CodeMirror.defineMode("rich", function(config, parserConfig) {
      var spellingError = {
        token: function(stream, state) {
          console.debug(stream);
          var ch;

```
      var re_url = /(www\.|(ftp|http?):\/\/)(-\.)?([^\s\?\.#-]+\.?)+([^\s]*)/;
      var re_word = /(.+ )/;
      if( stream.match(re_url)) {
        return "link";
      }else {
          var ch = stream.match(re_word);
          if (ch) {
              var res = ch[0].split(" ");
              if (!typo.check ( res[res.length-2] )){
                  return "spelling-error";
              }
          }
      }
      while (stream.next() != null && !stream.match(re_url, false) && ! stream.match(re_word, false) ) {}

      return null;
    }
  };
  return spellingError;
});
```

**Comment by callodacity** [comment]
@marijnh, I know this is a rather old thread - but I've written a spell-checker mode that integrates with node, and I'm running into a slight issue:

I'm using markdown as the base mode, and then I overlay the spell-check mode over it. 
The issue I have, is that I would like to keep both tokens on the highlighted word, example:

`**bold**` receives the bold token from the markdown mode.  
`mispelled` receives the misspelled token from the spell-check mode.  
But `**mispelled**` will receive the token from the spell-check mode, and *overwrite* the bold token from the markdown mode. I would like to keep both token classes on the word. 

Is there a particular option for this when overlaying a mode, or have I implemented it somewhere incorrectly?  
Or is this intended functionality? (If so, any pointers for a workaround would be helpful)
