### ISSUE TITLE
Code folding not working with Lua

### ISSUE THREAD

**Issue by weiqj** [codemirror/codemirror5#1922]
Using latest version of 3.19. Can't get code folding working with Lua.
Great product though. I still love it.

**Comment by creationix** [comment]
How do you add a folder?  I'm reading through the indent-folder and am trying to use it with lua (no it's not 100% correct, but it would give me a starting point).  I can't get the folds to do anything at all currently.

**Comment by creationix** [comment]
Nevermind, I figured it out.  The mode needs to opt into the folder with a "fold" property.

**Comment by marijnh** [comment]
Indeed. Basically, someone has to write a fold function that understanda Lua-style blocks, and then the lua mode needs to refer to that folder's name. (It might be possible to write one that works both for Lua and Ruby)
