### ISSUE TITLE
Composer.json

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [codemirror/codemirror5#1930]
Hi, how about a composer.json file for use in composer?

**Comment by tablatronix** [comment]
boo
:+1:

**Comment by tablatronix** [comment]
composer.json for installing codemirror for anyone else that needs it

```
{
    "require": {
        "codemirror/CodeMirror"      : "4.12.0"
    },
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "codemirror/CodeMirror",
                "version": "4.12.0",
                "source": {
                    "url": "git://github.com/codemirror/CodeMirror.git",
                    "type": "git",
                    "reference": "4.12.0"
                }
            }
        }
    ]    
}
```

**Comment by bfrohs** [comment]
@tablatronix Why wouldn't you just use:

```
{
	"repositories": [
		{
			"type": "vcs",
			"url": "git@github.com:codemirror/CodeMirror.git"
		}
	],
	"require": {
		"codemirror/CodeMirror": "4.12.*"
	}
}
```

**Comment by tablatronix** [comment]
yes, you are right, the new syntax is probably better , I used old verbose, I needed to parse it with legacy tools, and its easier.

**Comment by claviska** [comment]
@bfrohs That syntax only works if `composer.json` exists in the repo.

**Comment by marclaporte** [comment]
The current situation is that folks are getting outdated versions of CodeMirror:
https://packagist.org/search/?q=codemirror&orderBys%5B0%5D%5Bsort%5D=downloads&orderBys%5B0%5D%5Border%5D=desc

**Comment by marclaporte** [comment]
A potential option to explore:
https://asset-packagist.org/
https://asset-packagist.org/package/search?query=codemirror&platform=bower%2Cnpm

**Comment by marclaporte** [comment]
Dear Marijn,

JUSH got 126 000 installs: https://packagist.org/packages/vrana/jush by adding the file in March 2018: https://github.com/vrana/jush/commit/6f4e94d7660f1d610347e3b7871b0617d1cf5557

CodeMirror would be at hundreds of thousands of installs by now. Maybe more than 1 million like CKEditor: https://packagist.org/packages/ckeditor/ckeditor

In terms of sponsors: https://codemirror.net/6/
- Automattic is behind WordPress, a PHP project
- Wikimedia Foundation is behind MediaWiki, a PHP project

It's just one file. If it really is a problem, AUTHORS or CONTRIBUTING.md could be moved in a directory, and referred to in the README

Thanks!

Marc
