### ISSUE TITLE
Get and set position/ranges/selections by character index

### ISSUE THREAD

**Issue by ghost** [codemirror/codemirror5#201]
Hi,

I'm sure this is probably an obvious question but I'll ask it anyway...

I need to be able to get and set positions/ranges/selections based on the number of characters from the start of the text. I know you can do this with getCursor, setCursor, getRange, replaceRange, setSelection, however you have to specify line and char. Is there a way do just use an index (which is the common way to work with strings), otherwise it means having to somehow convert an index to a line/char combination?

Thanks in advance... I'm loving CodeMirror 2.

**Comment by basarat** [comment]
Updated link to PR : https://github.com/codemirror/CodeMirror/pull/203 (previous link 404ed)
