### ISSUE TITLE
[v4] overlayMode

### ISSUE THREAD

**Issue by heruan** [codemirror/codemirror5#2015]
In `v4` branch modes `gfm` and `rst` call `CodeMirror.overlayMode` which seems to be undefined.

**Comment by samueleaton** [comment]
This is happening again for GFM

**Comment by marijnh** [comment]
Only if you are including the files manually with script tags and forget to include the overlay mode dependency.

**Comment by RudeySH** [comment]
The documentation for the `gfm` mode could use some clarification about this. For future readers, you need to include `addon/mode/overlay.js`, `mode/markdown/markdown.js`, and of course `mode/markdown/gfm.js`.
