### ISSUE TITLE
Access editor instance from inside a mode

### ISSUE THREAD

**Issue by foo123** [codemirror/codemirror5#2032]
Hi Marijnh,

continue to work on the codemirror-grammar add-on, trying to implement smart indentation, defined by the user in the grammar.

The simple, intuitive way is for tokens (or group of tokens) to be able to have an associated "action" (which initially will be of 2 types "indent" and "outdent" ), either before or after a specific token sequence is identified.

The first part is almost complete, however to implement this feature, a way is needed for the mode to call the indent handler (or in some way access the editor instance) so it can call methods when needed.

Is there a way or a work-around, cant seem to find anything  in the code or manual for this case.

Thanks

**Comment by foo123** [comment]
Hello again, instead of opening another issue, i found this old issue and continue sth (if needed can opne a new one).

The codemirror-grannar add-on has new versions with interesting and important features (including a full grammar specification in BNF form and context-specific actions,..smart indentation is going to be added as well).

i need some things to be able to make some actions or tokens work correctly.

1. the current line number (in the source code) that is currently being edited (cant find it anywhere)
2. and/or a way to determine SOF (start of file, meaning the very start of the very first line) and not SOL (start of line)

Thank you.

**Comment by marijnh** [comment]
You can pass a reference to your editor instance as a parameter to your mode, if you really want to. But most of the things that you can do with an editor you __really should not__ do from a mode, so this is rarely a good idea.

You can't get the current line number and you won't ever be able to get the current line number because the way modes work, their output can be reused even as lines shift up and down in the editor. You can keep a counter in your mode state counting how many lines it has seen, but this isn't guaranteed to correspond to the actual line number of the parsed text.

Figuring out the start of the file is easy. Just set a flag in your starting state for the mode, and clear it the first time the token method is ever called on a state.

**Comment by foo123** [comment]
Yes i'm aware of both the issues you raise.

For example, line numbering *might be an issue* for inner modes as well, however it is easily resolved since codemirror manages inner modes switching and keeps line counts (maybe this requires a few extra code but still straight-forward)

i would say it is potentialy a good idea (for example ACE passes the row number, maybe different from line number per se) since it enables highlighting in new ways and with new conditions

i'm also aware of the startState method to keep track of SOF (i usualy check the source code before posting issues) but in the source code it seems startState method can be called multiple times (for example if no state is found, CodeMirror 2.0 is what i use to test), so this is confusing.

It is good that one can use the startState to signal SOF, but is it actualy correct?

Thanks again, Marijnh

(ps if you will, consider the issue i opened for a reference to codemirror-grammar add-on in codemirror)

**Comment by marijnh** [comment]
> It is good that one can use the startState to signal SOF, but is it actualy correct?

It is, if you do it right. First, read [this blog post](http://marijnhaverbeke.nl/blog/codemirror-mode-system.html) so that you know what's going on. You can have `startState` return something like `{sof: true}`, and then, whenever you read a token, update your state `state.sof = false` so that you know you're no longer at the start of the document.

**Comment by foo123** [comment]
Yes i've read that too

btw 

> I've been waiting for a common standard for such specifications to emerge, but not much progress seems to be made there.

codemirror-grammar add-on (the reason for this issue as well) **solves this problem** as well as the **problem of extending existing modes** to handle variations and new dialects in an optimum way,

It solves the porblem in two ways

1. Full-featured Grammar specifications, handling lexical, syntax analysis and actions to a great detail
2. Grammar is intuitive and descriptive
3. Grammar is JSON format and can be extended/merged with other grammars as needed

Now about the issue, yes but can SOF flag be maintained in the entire line, not just the first token?

Having SOF indicate the entire line then using `stream.sol()` is easy to get the start of the line. but is important to be able to maintain SOF on the entire first line as whole, not just until first token. Hope it is clear.

This is where i'm having problems and a line number or row number would immediately solve this easily

The reason this is extremely useful is that there are cases where some code can only be placed first (or in the first non-empty line), e.g `<doctype>` in `xml/html` and not elsewhere, so this provides better highlighting abilities

**Comment by marijnh** [comment]
So clear the start-of-file flag only at the end of the first line, if you need to know when you're on the first line. Or if the conditions are more complex, write your code to clear the flag after reading the appropriate token.

**Comment by foo123** [comment]
Ok, i'll try that and see.

Still, consider the issue of passing line numbers or at least row numbers (in the sense of relative line number vs absolute line number) to highlight modes (have added a comment on the issue of new features about this as well). It can give new highlighting abilities with less clutter.

Thanks again, cheers!
