### ISSUE TITLE
[sql] Indentation failure

### ISSUE THREAD

**Issue by peterkroon** [codemirror/codemirror5#2064]
Chrome stable Windows 7 32
- Go to: http://codemirror.net/mode/sql/index.html?mime=text/x-plsql
- Place cursor in editor via mouse
- `Ctrl-A` => and paste the given code below in the editor

``` sql
CREATE TABLE __codemirror_test(
```
- Place cursor via mouse after `(`
- `Ctrl-A` => `Tab` => `Shift-Tab`

The code will not reindent.

**Comment by marijnh** [comment]
I've reconsidered this, and concluded that the old behavior is actually more sensible (given that the mode doesn't do any intelligent indentation, it might as well just leave the existing indentation alone). So attached patch goes back to returning `CodeMirror.Pass`.
