### ISSUE TITLE
HighlightJS language to CodeMirror mode adapter

### ISSUE THREAD

**Issue by hitsthings** [codemirror/codemirror5#2137]
I'm in the process of switching from a system that used HighlightJS to one that uses CodeMirror (and CodeMirror modes) for syntax highlighting.

hljs languages are declarative using regexs to enter and exit from states (where entering essentially opens a wrapping element, and exiting ends the element). This wrapping and unwrapping aspect is nice - it means you can straight-forwardly apply, for example, a background color to everything inside an HTML tag. ![hljs example](https://monosnap.com/image/eiq2gWn0yo7jwzlwdA763DlrU.png)

The declarative bit means I think I could write a single CM mode that would adapt hljs languages to run against CodeMirror instances. The caveat is that all classes would end up on the same single wrapping element - there is no nesting/wrapping in CM - and therefore the existing hljs themes, which might have selectors like `.tag > .value`, won't apply correctly into the CodeMirror instance. They'll need some massaging.

Is my assumption that I can't nest elements in a mode correct? Should I also assume you have no interest in adding support for that?

Given the above caveats to a fully-functional hljs adapter, would you be interested in an hljs adapter add-on in this repo or is it something better left in my own codebase?

Any suggestions/advice/previous conversations you could share would be greatly appreciated.

Thanks!
Adam

**Comment by dhowe** [comment]
Not sure if I missed the conclusion above, but is there a way (via an adapter) to use a highlight.js specification in a codemirror editor instance? I'd rather not rewrite the highlight.js code spec in codemirror (even if its its easy) as I then have two codebases to to keep in sync.

**Comment by marijnh** [comment]
No, there still isn't such a thing, as far as I know—no one appears to have worked on it.
