### ISSUE TITLE
Markdown header issue.

### ISSUE THREAD

**Issue by lukasoppermann** [codemirror/codemirror5#2143]
Hey,

I think I found a "bug" in markdown.

When I type the following, only the `=====` gets classes for being a header, and the text `Header` does not. I think either both should get this class or none of the two, or maybe the `======` could get an additionally class, if neither of the above work. Otherwise it makes it hard to style correctly. Thanks.

```
Header
======
```

**Comment by brondsem** [comment]
As a workaround, you can style the previous lines with this snippet in your own code.  I'm not sure if there would be an appropriate place to include this as part of the built-in markdown mode.

```javascript
function updateSectionHeaderStyles(cm, change) {
  var lines = cm.lineCount();
  for (var i = Math.max(0, change.from.line-1); i <= Math.min(change.to.line+1, lines-1); i++) {
    var line = cm.getLineHandle(i);
    cm.removeLineClass(line, 'text', 'cm-header');
    cm.removeLineClass(line, 'text', 'cm-header-1');
    cm.removeLineClass(line, 'text', 'cm-header-2');
    var lineTokens = cm.getLineTokens(i);
    var tok = lineTokens[0];
    if (!tok || !tok.type || tok.type.indexOf('header') === -1) {
      // first token could be some spaces, try 2nd
      tok = lineTokens[1];
    }
    if (tok && tok.type && tok.type.indexOf('header') !== -1
      && tok.string !== '#') { // not ATX header style, which starts with #
      var classes = tok.type.
        split(' ').
        filter(function(cls) { return cls.indexOf('header') === 0; }).
        map(function (cls) { return 'cm-' + cls; }).
        join(' ');
      var prev_line = cm.getLineHandle(i-1);
      cm.addLineClass(prev_line, 'text', classes);
    }
  }
}
myCodeMirror.on("change", updateSectionHeaderStyles);
updateSectionHeaderStyles(myCodeMirror, {from: {line: 0}, to: {line: myCodeMirror.lineCount()}});
```

**Comment by tobloef** [comment]
Any possibility of this issues getting reopened as a feature request? It would be very nice if the workaround posted by brondsem was native to CodeMirror.

**Comment by dwelle** [comment]
Made a quick naive fix [over here](https://github.com/dwelle/CodeMirror/commit/7cb4e1588119835c37fb4b8e981625ac4ea95cdc). It's still not 100% CM-compliant, but it fixes styling for the line immediately before the `------` setext line.

Also not sure if it doesn't have some major performance implications. Do we have some perf benchmarks we could run on this?
