### ISSUE TITLE
How Do I Insert Change Objects Captured In Another Codemirror Document

### ISSUE THREAD

**Issue by bvallelunga** [codemirror/codemirror5#2147]
I am building a realtime collab and am using codemirror. How do i insert a list of change objects into another editor. Both editors started with the same content and am trying to replicate what happens on one editor to the other. Thank you in advance for any help you will give. 

@marijnh if you have the time, could you take a quick second and look at this? Help would be much appreciated. I really love codemirror and I think this issue has a really simple answer but all of my research has resulted in nothing informative. Thanks!

**Comment by dongpei021** [comment]
This works. Weird not included in documentation.

**Comment by marijnh** [comment]
This isn't the case anymore in recent versions of the library, so of course the current docs don't talk about it.

**Comment by dongpei021** [comment]
oh, I am using a old version. Thanks
