### ISSUE TITLE
[JS] Style function names, function arguments, and function calls.

### ISSUE THREAD

**Issue by timimahoney** [codemirror/codemirror5#2164]
It would be nice to be able to style function names and arguments differently from other variables and definitions. Take the following example:

``` js
function functionName(argumentName) {
    var variableName = 0;
    this.doSomething(2);
}
```
- `functionName` is considered a `cm-variable`, and this is technically true. However, it would be nice to style the `functionName` token differently from other `cm-variable` tokens.
- `argumentName` and `variableName` will be styled as `cm-def`. It would be nice for `argumentName` to be considered `cm-argument` or something that we can style differently than a plain `cm-def`.
- `doSomething` is styled as a `cm-property`, which again is technically true. However, it would be nice to be able to distinguish normal properties from properties called as functions.

**Comment by karlhorky** [comment]
> I know some people like to have many, many different colors in their code as a kind of visual pattern matching aid
>
> It is, however, very easy to use a local fork of `mode/javascript/javascript.js`

@marijnh are you aware of any public forks that have added extra coloring for different parts of JavaScript code, such as function names, variables which are functions vs non-function variables, different keywords such as `export`, `default`, `return`, class-like variables etc?

It's a pretty common thing for syntax highlighters to have now, eg. take a look at VS Code's default dark theme:

<img width="514" alt="Screen Shot 2022-01-02 at 13 13 53" src="https://user-images.githubusercontent.com/1935696/147875356-6e72ab1f-74b8-42c0-832f-ba49f1401382.png">

**Comment by karlhorky** [comment]
Oh, found the `codemirror.next` repo just now, wonder if this is more up to date... made a comment over there too: https://github.com/codemirror/codemirror.next/issues/284#issuecomment-1003718135
