### ISSUE TITLE
Part of CodeMirror disappears temporarily

### ISSUE THREAD

**Issue by iclems** [codemirror/codemirror5#2195]
I've been reproducing again and again a weird bug, in Chrome, since the release 32.0.1700.102 (it really seems related IMO). Is anyone else facing similar issues? If so, we could open a Chrome issue, but I would like first to see if other people (not using Firepad ?) are facing the same kind of issues. 

It happens but gets back to normal if you type again something, or scroll.

![capture decran 2014-01-30 a 19 24 45](https://f.cloud.github.com/assets/1120050/2043263/6a0fe866-89dc-11e3-8c25-27c4e6f117ca.jpg)

**Comment by BurnTurn** [comment]
This issue is prominent in Postman, although they are using a very(!) old version of CodeMirror, i.e., v2.38. Does anyone know if this issue was ever identified and resolved? If so, could you please point me to the commit or version in which it was dixed? Thanks!

**Comment by prdonahue** [comment]
This issue is prominent in Postman, although they are using a very(!) old version of CodeMirror, i.e., v2.38. Does anyone know if this issue was ever identified and resolved? If so, could you please point me to the commit or version in which it was fixed? Thanks!

**Comment by marijnh** [comment]
@prdonahue Definitely try upgrading. The display update mechanism has been rewritten in the meantime.
