### ISSUE TITLE
[v4] Expose adjustForChange() publicly

### ISSUE THREAD

**Issue by njx** [codemirror/codemirror5#2220]
I'm starting to write a number of edit ops that apply to multiple selections, and it would be handy to have `adjustForChange()` publicly available, since I basically need that logic in order to adjust a set of ranges (which might or might not correspond to the actual selection in the editor) after doing a single edit. Would there be any problem with exposing that publicly?

**Comment by flaki** [comment]
Hi! Can I ask for this to be reconsidered, or the "interface creep" to be somehow worked around? This is a very handy function, and in its implementation not immediately straightforward (and I just accidentally stumbled upon the function itself in the source, which solved my problem immediately). I expect exposing it would be more useful than not.
Thank you for your consideration Marjin and sorry to bring this up again!
