### ISSUE TITLE
Javascript NO-BREAK SPACE \u00a0 is converting to Â character

### ISSUE THREAD

**Issue by scverano** [codemirror/codemirror5#2276]
Hi, I encountered this problem when I update our CodeMirror library from 0.9 to 3.21

The cursors space is also converted to Â character

![screenshot](http://gyazo.com/15ea282eb9f011b0052269d1df567233.png)

**Comment by lax4mike** [comment]
Here is the solution: http://blog.entelect.co.za/view/6435/minification-and-why-i-m-seeing-instead-of-whitespace

**Comment by bultas** [comment]
solution that works for me was add meta charset UTF8 to html file where you load js file

`<meta charset="UTF-8">`

**Comment by mikecrittenden** [comment]
@bultas's solution worked for me as well.

**Comment by SebastianKrieger** [comment]
I do see the exact same behavior using codeMirror react and webpack+uglify.
I used `<meta charset="UTF-8">` in html as well as output: {ascii_only: true} in uglify option in webpack.
Both did not fix the issue... Did anyone fixed it another way?
