### ISSUE TITLE
[vim] Implement insert mode <Ctrl-r> to insert the contents of a register

### ISSUE THREAD

**Issue by dbarnett** [codemirror/codemirror5#2298]
In vim, I can paste previously yanked text without leaving insert mode with `<Ctrl-r>"`. Similarly for other registers like `%` (current file name), `-` (last small delete), and `=` (arbitrary vimscript expression entered at resulting prompt).

CodeMirror doesn't support this. Pressing `<Ctrl-r>` in insert mode tries to reload the page, even for Chrome apps opened as a standalone window.

**Comment by Marceline** [comment]
Apologies for chiming in with inexperience, but, I'd love to see this issue resolved. It's just a bonus that I get to do it myself.

Any recommendations as to a good place to start ?

Cheers

**Comment by marijnh** [comment]
The vim code is now being maintained at https://github.com/replit/codemirror-vim/ . If this is still important, check whether there is an issue open for it there.
