### ISSUE TITLE
[vim] Support \c and \C in search patterns

### ISSUE THREAD

**Issue by dbarnett** [codemirror/codemirror5#2302]
Vim patterns support a special `\c` symbol to change patterns so they're evaluated case-insensitvely, as if the 'ignorecase' setting were enabled. `\C` explicitly enables case sensitivity for a pattern.

It would be nice if CodeMirror supported `\c` and `\C` in patterns.

**Comment by Archie-2021** [comment]
+1 for this

**Comment by marijnh** [comment]
The vim code is now being maintained at https://github.com/replit/codemirror-vim/ . If this is still important, check whether there is an issue open for it there.
