### ISSUE TITLE
[vim] Support CTRL-] to jump to tags

### ISSUE THREAD

**Issue by dbarnett** [codemirror/codemirror5#2303]
In vim, pressing `<Ctrl-]>` in normal mode searches for the tag under the cursor and jumps to the location.

`<Ctrl-]>` in CodeMirror doesn't seem to have any effect. It would be nice if it triggered jumping to definitions when CodeMirror is embedded in a host app where that makes sense. That would probably involve hooking into the host app somehow if CodeMirror doesn't have its own model for tags/definitions.

**Comment by marijnh** [comment]
The vim code is now being maintained at https://github.com/replit/codemirror-vim/ . If this is still important, check whether there is an issue open for it there.
