### ISSUE TITLE
[vim] Implement vim CTRL-X completion

### ISSUE THREAD

**Issue by dbarnett** [codemirror/codemirror5#2306]
Vim has its own insert-completion feature with several different varieties of completion. Even if there's already some standard completion in CodeMirror using Ctrl-Space, it would be nice to be able to e.g., complete only words from the current file using `i_CTRL-X_CTRL-N`, or words from other active buffers using `i_CTRL-N`.

**Comment by marijnh** [comment]
The vim code is now being maintained at https://github.com/replit/codemirror-vim/ . If this is still important, check whether there is an issue open for it there.
