### ISSUE TITLE
Mac Chrome 34 breaks scrolling by dragging the scrollbar

### ISSUE THREAD

**Issue by mtaran-google** [codemirror/codemirror5#2326]
I'm hoping you can come up with a small test case and help figure out what the issue is: https://code.google.com/p/chromium/issues/detail?id=348745

**Comment by marijnh** [comment]
Just a heads-up that, I suppose due to further changes in the way OS X does scrollbars, I had to revise my strategy here again. Attached patch moves back to a `pointer-events` solution, but improves the old approach by temporarily enabling pointer events after scrolling.

**Comment by johnjbarton** [comment]
Please see #3677
