### ISSUE TITLE
Doubleclicking a $var should select the whole thing

### ISSUE THREAD

**Issue by marcelgerber** [codemirror/codemirror5#2426]
(Filed as adobe/brackets#7370)
1. In http://codemirror.net/demo/complete.html, enter `$test = true;`
2. Doubleclick `$test`

Expected: `$test` should be selected
Result: `test` is selected, `$` not. Such variable names are common practice with jQuery, PHP and Perl.

**Comment by HelgeSverre** [comment]
Would love the option to pass wordChars as a parameter to the findWordAt function, and fallback on the default, I think  that is a more flexible approach.
