### ISSUE TITLE
Shift-Tab not tabbing back

### ISSUE THREAD

**Issue by joelmoss** [codemirror/codemirror5#2428]
If I have two tabs and hit `Shift-Tab` I expect to go back a tab, but instead I am taken back to the beginning of the line, no matter how many tabs I have on that line.

Is this intended behaviour or a bug? I'm not sure.

**Comment by polkovnikov-ph** [comment]
I know about this issue for several years, but as nobody commented I feel like I should. This is not expected and obvious behaviour. Most editors unindent on Shift+Tab.

**Comment by erquhart** [comment]
In case others run into this, I didn't find a `keyMap` property on the CodeMirror instance, but the [`extraKeys` config](https://codemirror.net/doc/manual.html#option_extraKeys) can also be used, as demonstrated in the [PR referenced above](https://github.com/StackExchange/StackExchange.DataExplorer/pull/58/files#diff-02bf0ef97f863cef2592069c4cd3f3c5R32).

**Comment by marijnh** [comment]
>  I didn't find a keyMap property on the CodeMirror instance

It's not on instances, it's on the class/constructor object.

**Comment by erquhart** [comment]
Ah, thank you. Is that API in the docs?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by marijnh** [comment]
It's mentioned in [the docs for the `on` method](https://codemirror.net/doc/manual.html#on)

**Comment by erquhart** [comment]
Got it, really good to know, thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by CrashLaker** [comment]
thank you @erquhart using extraKeys worked for me :)
