### ISSUE TITLE
Codemirror editor is not loading content until clicked

### ISSUE THREAD

**Issue by parameswarmal** [codemirror/codemirror5#2469]
I am using codemirror 4 with bootstrap 3. In my bootstrap modal, there is a textarea, and i am replacing it with codemirror. I am using cm.setValue('initial value') to initialise codemirror with an input. The problem is that the content is there, but it is not visible until it is clicked. i am using cm.refresh() but it is not working.Please advice

**Comment by thealjey** [comment]
Just in case, and for everyone who doesn't read the documentation carefully enough (like me), but stumbles upon this.
There's an [autorefresh addon](http://codemirror.net/doc/manual.html#addon_autorefresh) just for that.
Works like a charm :trophy:

**Comment by Real-Gecko** [comment]
+1 for autorefresh addon, really handy.

**Comment by zhouboluo** [comment]
Same question. And I also used modal.   The autorefresh:true, refresh() and focus() all don`t work. How can I do?

**Comment by martinwojtus** [comment]
I have simple (but not very elegant) solution for this problem -> call $('.CodeMirror-code').html(''); before modal is shown.

**Comment by lee2seek** [comment]
```javascript
setTimeout(function() {
   editor.refresh();
},1);
```

**Comment by wilcoln** [comment]
> Just in case, and for everyone who doesn't read the documentation carefully enough (like me), but stumbles upon this.
> There's an [autorefresh addon](http://codemirror.net/doc/manual.html#addon_autorefresh) just for that.
> Works like a charm

Thanks! you saved the day.

**Comment by voidgraphics** [comment]
Should this really be closed? Is there really no possible way to make it work without calling `refresh()` after the editor becomes visible? It's a bit of a pain and in some situations can be impossible/very unpractical. 

If anyone has more insight into what causes the problem, maybe I can try looking at it and submitting a PR. This bug has been haunting me for years.

**Comment by viseth** [comment]
Hi,

The add-on works like a charm when we need to refresh only one time. 
Now if the textarea needs to be refresh a second time... For instance new content has been set, then the value of the codemirror instance is set but it is not shown until we click the textarea.

Please advice,
Thanks,

**Comment by z8772083** [comment]
same with u @viseth

**Comment by JaDogg** [comment]
If you are using a bootstrap (I'm using 4.0) modal for example try this. This is the only thing that worked for me. 

```java
    $('#myModal').on('shown.bs.modal', function (e) {
          console.log('refresh');
          myCodeMirror.refresh();
    });
```
