### ISSUE TITLE
Feature Request: Ctrl+Drag to copy text

### ISSUE THREAD

**Issue by SLaks** [codemirror/codemirror5#2556]
If I start dragging a selection, then hold down Ctrl while dropping, can you copy the text instead of moving it?

(most editors allow you to hold down Ctrl during the entire drag; you can't do that because of multiple selection)

**Comment by Frigory33** [comment]
Hello,
I am interested in this feature as I use it very often.
Your implementation doesn't work for me on Firefox (but it works well on Chromium). It simply moves the text ignoring Ctrl, or in worst cases, if you put your mouse at the wrong place (there are such places in the editor), it will open your text as an URL in the current tab.
Hoping to help.

**Comment by marijnh** [comment]
Attached two patches should greatly improve drag-drop on Firefox.

As for middle-click paste, that's unfortunately not something that Firefox make possible (it doesn't fire any events we can capture when this happens, whereas Chrome fires a regular paste event.)

**Comment by Frigory33** [comment]
Much thanks for your fix.
I think Firefox fires a mousedown event: http://api.jquery.com/mousedown/
unless a menu (like the contextual menu) is open. But it still shows the scrolling tool.
