### ISSUE TITLE
Copy text in readOnly 'nocursor' mode

### ISSUE THREAD

**Issue by sofiushko** [codemirror/codemirror5#2568]
Hi, i can copy text in readOnly:true mode(although it's not stable with context menu and also i see 'past' in it).
But i don't need cursor. And in readOnly:'nocursor' mode i can not copy at all.
Can you do it?

**Comment by mindjuice** [comment]
You can hide the cursor by setting `cursorBlinkRate` to a negative number in the options.  Not sure if this was the case when you posted this, but I'm adding this since I found this post by Googling `CodeMirror hide cursor` and later found the answer.
