### ISSUE TITLE
why remove bower.json's version?

### ISSUE THREAD

**Issue by laurelnaiad** [codemirror/codemirror5#2569]
How is it helping to omit the version from bower.json?

It renders bower incapable of knowing which version you have locally and thus incapable of following your bower.json file's instructions to update the component... thus every app that references codemirror through bower gets locked to the version that a particular user happened to get when they first ran bower install on one's repo.... 

https://github.com/marijnh/CodeMirror/commit/82b62f3bce55d081f9a7c2f9bc5ed0f11f26d7b3#diff-0a08a7565aba4405282251491979bb6bL3

This seems to be altogether counterproductive.

**Comment by kkirsche** [comment]
Also their maintainer says they probably won't ever use it: http://stackoverflow.com/questions/24844901/bowers-bower-json-file-version-property
