### ISSUE TITLE
Line classes appear to be doc specific but there is only an editor removal method?

### ISSUE THREAD

**Issue by CareyJWilliams** [codemirror/codemirror5#2573]
There is an editor.removeLineClass but no doc.removeLineClass method.
This would be fine except for the fact that line classes seem to be document specific for me, i.e. if I add a line class then swap to a new document, fire removeLineClass and then swap back - the line classes are still in effect on that first document.

Is there any chance that we could get a doc.removeLineClass method or make line classes editor specific? The former would be preferable but either would be a big help!

I'm using version: 3.19.0

Cheers

**Comment by CareyJWilliams** [comment]
@marijnh Just stumbled across something that may be related:
addLineWidget only works on CodeMirror (cm) instances, but again it appears to be tied to the doc instance (so swapping an editor's doc removes the widget, and swapping back to the original doc replaces it).

Is this intentional?

**Comment by marijnh** [comment]
That's a good point. Patch 31b9f1b moves it.
