### ISSUE TITLE
swift support

### ISSUE THREAD

**Issue by MasseGuillaume** [codemirror/codemirror5#2605]
add swift mode 

Grammar:
https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/Swift_Programming_Language/zzSummaryOfTheGrammar.html#//apple_ref/doc/uid/TP40014097-CH38-XID_1030

**Comment by jeeftor** [comment]
@mkaminsky11  - How close are you being ready to do a pull request?

**Comment by mkaminsky11** [comment]
I think that it's done, I just never thought of submitting one...I will, though
