### ISSUE TITLE
[vim] Yank lines

### ISSUE THREAD

**Issue by sirex** [codemirror/codemirror5#2643]
In vim, `Y` yanks whole line, but in CodeMirror with vim mode, `Y` yanks text from current cursor position to end of line (`y$` in real vim).

You can reproduce it in CodeeMirror with vim mode by typing these keys: `Yp`. It should paste whole line, below.

**Comment by dsummersl** [comment]
It would be helpful to know how to override codemirror's behavior here; I've found the non-vim/non-vi behavior of `Y` quite interrupts my workflow. Anyone have a snippet they could share to change this setting?

**Comment by adrianheine** [comment]
I actually fixed that in 3126d9df613b03ef831ef73b31c47c967f6c4536#diff-6dc93a20c528b2867b24cce681ef9872.
