### ISSUE TITLE
CSS transitions are destroying the gutter

### ISSUE THREAD

**Issue by JulianAnthes** [codemirror/codemirror5#2667]
CSS

```
.CodeMirror * {
    transition: all 0.2s cubic-bezier(0.7, 0, 0.175, 1) 0s;
}
```

Results in this

![codemirror-bug](https://cloud.githubusercontent.com/assets/3493187/3412957/2eb62138-fe06-11e3-86ea-22d320402af2.jpg)

Both are created from a textarea like this:

```
$('.spl-initCodeMirror').each(function(index) 
    {
        window['editor'+index] = new CodeMirror.fromTextArea( this, 
        {
            mode: 'text/html',
            readOnly: true,
            //theme: "monokai",
            autoClearEmptyLines: true,
            lineWrapping: true,
             styleActiveLine: true,
            matchBrackets: true,
            lineNumbers: true
        });
    });
```

I've figured out how to work arround the issue with this:

```
setTimeout(function() 
{
    window['editor'+index].refresh();
}, 250);
```

**Comment by tanggd** [comment]
I also encountered this problem.
The refresh method can't solve the problem either. There is always a problem that some code is not displayed when setting the height dynamically.
![image](https://github.com/codemirror/codemirror5/assets/23456667/e36e9685-a5f0-4a3a-990b-57e6ab07c10e)

Has anyone already solved this problem?
