### ISSUE TITLE
Get DOM element from marked text

### ISSUE THREAD

**Issue by donpinkus** [codemirror/codemirror5#2707]
I've used doc.markText() to mark a specific variable in my CodeMirror. How can I get the DOM element for this mark? I've been looking through the mark object returned by `markText()` and I haven't noticed any method or attribute.

```
window.myEditor.marks[i] = myCodeMirrorInstance.markText(
        {line: myLineNum, ch: myToken.start}, 
        {line: myLineNum, ch: myToken.end},
        {className: "foobar"}
    );
```

At this point I've saved the mark to be globally accessible. I'm wondering if I Code Mirror has something like `window.myEditor.marks[i].getDOMElement()`. Thanks!

**Comment by jchook** [comment]
I worked around this by setting `title` to something like 'HAX' and then finding the span via jQuery with `$('span[title="HAX"]')`. Seems like a missing feature although perhaps it's intentional to avoid add-ons that rely on manual DOM manipulation.

**Comment by erez-sense** [comment]
I would be more than happy to get the DOM element from `cursorActivity` event in the codemirror object as `lastElementClicked`.
