### ISSUE TITLE
Mode-to-add: Template Toolkit

### ISSUE THREAD

**Issue by ianmcorvidae** [codemirror/codemirror5#2727]
Template Toolkit (http://template-toolkit.org/) is one of the most prominent (probably the most prominent) template languages used in Perl, especially for web applications. Generally it's in files with extension `.tt` or `.tt2`. Often used for templating HTML, as noted; TT-specific markers are bits like `[% %]` (sometimes with extra characters to denote comments or for whitespace control).

One example file (on bitbucket, where codemirror is used): https://bitbucket.org/metabrainz/musicbrainz-server/src/beta/root/layout.tt

**Comment by kylemhall** [comment]
Where do mode requests go now? That wiki link is  no longer active.

**Comment by marijnh** [comment]
There's no chance of mode requests being implemented anymore. Write and distribute the mode you need as a separate package.
