### ISSUE TITLE
Hack-lang syntax support (HHVM, facebook's php)

### ISSUE THREAD

**Issue by RdeWilde** [codemirror/codemirror5#2756]
Please add support for hack-lang, the language developed by mainly Facebook with their HHVM PHP-engine.

http://hhvm.com/blog/4223/introducing-hack-a-programming-language-for-hhvm

Jetbrains PHPStorm is about to add it in their new version:
http://youtrack.jetbrains.com/issue/WI-21737

**Comment by toddmcbrearty** [comment]
This is a big one
+1
