### ISSUE TITLE
state.curMode.indent undefined is not a function

### ISSUE THREAD

**Issue by muxahuk** [codemirror/codemirror5#2825]
Hello,

I get "undefined is not a function" in mods file "php.js" on line 219.
I get it when i hit enter and text jumps on new line.

Could you explane what could i do wrong ? ( i'm adding modes in codemirror.js file at the end ).

I need only few mods along with php i'v added: css, javascript, html and php ( in that same order )

And if i download compressed version ( with mods included ) then i get same error "undefined is not a function" but now it apperas not in php.js, but somewere else, becouse it fiers on pageload ( ready ).

Thanks.

**Comment by addui** [comment]
This error is still happening for me

**Comment by marijnh** [comment]
@addui So load the modes that the PHP mode depends on, as @muxahuk mentioned.

**Comment by addui** [comment]
Shouldn't they be automatically loaded with the PHP mode? therefore isn't this a bug? therefore isn't this worth reporting and shouldn't be closed yet?

**Comment by marijnh** [comment]
It will, if you use a module loader of some kind. If you're using plain `<script>` tags, you have to take care of dependencies yourself.

**Comment by addui** [comment]
Even I wanted to load the module I wouldn't know which one it was because he simply stated that he forgot to load a module that it depends on but never said which one.

**Comment by marijnh** [comment]
You could look at the docs for the [the php mode](http://codemirror.net/mode/php/), which list the modes it depends on.

**Comment by muxahuk** [comment]
> Depends on XML, JavaScript, CSS, HTMLMixed, and C-like modes
