### ISSUE TITLE
Leader key a thing?

### ISSUE THREAD

**Issue by jondkinney** [codemirror/codemirror5#2841]
Is there any concept of a leader key in CodeMirror's vim implementation?

I'd love to be able to set a custom mapping (like I can in my .vimrc) for something like `<leader>ciw` which I'd use to toggle code comments on and off. Also, is there a default way to commend out some code (say a visually selected block of code) when in vim mode? The `<leader>ciw` I mentioned earlier is from NerdCommenter so I'm trying to figure out how to best replicate that.

I'm using CodeMirror through Codio if that makes a difference.

Thanks!

**Comment by jgors** [comment]
any update on having a vim style leader key implemented?

**Comment by marijnh** [comment]
The Vim bindings are without a maintainer at the moment, so don't hold your breath waiting for new features.

**Comment by xeruf** [comment]
How does one create a custom key map at all, though? I struggle to find documentation.
Only found this: https://codemirror.net/demo/vim.html

**Comment by marijnh** [comment]
The vim code is now being maintained at https://github.com/replit/codemirror-vim/ . If this is still important, check whether there is an issue open for it there.
