### ISSUE TITLE
onGutterHover

### ISSUE THREAD

**Issue by tmcw** [codemirror/codemirror5#335]
Does it seem reasonable to add an `onGutterHover` callback to CodeMirror, in addition to `onGutterClick`? I might be able to work on a pull request if it's useful - in one case ( mapbox/tilemill#852 ) it's useful to activate a gutter's content on hover to quickly glance at per-line error reporting.

**Comment by rakeshrohan** [comment]
Hey @marijnh is this still valid if i want to use hover on gutter? 
Because it says connect is not method for codemirror 5.5
i will not be able to upgrade due to organization's policies. Could you please let me know how to proceed?

**Comment by marijnh** [comment]
You can use `CodeMirror.on` instead of `CodeMirror.connect` in recent versions.
