### ISSUE TITLE
OnChange Save() 

### ISSUE THREAD

**Issue by svennis94** [codemirror/codemirror5#381]
Hi,

I can't figure out what i am doing wrong. Firebug doesn't give an error but when i change the text in the codemirror editor it won't put it in the hidden textarea.

``` javascript
var editor = CodeMirror.fromTextArea(document.getElementById("code"), {
  mode: "mustache",
  lineNumbers: true,
  lineWrapping: true,
  electricChars: false,
  onChange: function(){editor.save()},
  onCursorActivity: function() {
    editor.setLineClass(hlLine, null);
    hlLine = editor.setLineClass(editor.getCursor().line, "activeline");
  }
});
```

Why doesn't the text from de codemirror editor go to the hidden textarea?

**Comment by dennizvd** [comment]
I have the same issue.. 

I try to save in textarea CodeItemNEW1 using `onChange: function(){ editor1.save()}` but it's not added to it when i look in dev tool. I don't see it added anywhere also not in another textarea. Help? :P

 var editor1 = CodeMirror.fromTextArea(document.getElementById("CodeItemNEW1"), { mode: "text/html", theme: "eclipse", lineWrapping: true, styleActiveLine: true, matchBrackets: true, readOnly: false, onChange: function(){ editor1.save()} }); var charWidth = editor1.defaultCharWidth(), basePadding = 4; editor1.on("renderLine", function(cm, line, elt) { var off = CodeMirror.countColumn(line.text, null, cm.getOption("tabSize")) * charWidth; elt.style.textIndent = "-" + off + "px"; elt.style.paddingLeft = (basePadding + off) + "px"; }); editor1.refresh(); $("#idLanguage1").change(function(){ editor1.setOption("mode", $(this).val() ); });

**Comment by dennizvd** [comment]
Sorry sometimes I post a question to fast and a little bit later I find the solution. In this case it was: `editor1.getValue();`
