### ISSUE TITLE
Backspace tab-deleting behavior in vim mode

### ISSUE THREAD

**Issue by vincentwoo** [codemirror/codemirror5#3963]
I got this report from a user that was so well written I'm just going to deposit it verbatim here:

> One concern regarding the vim key bindings:
> 
> Python is whitespace sensitive. A problem I'm having with the Vim key bindings is that when I type o to go into edit mode after inserting a new line and then hit backspace, it backspaces a single space, rather than a 4-space "tab". This is counter to how vim actually behaves when using soft tab stops.
> ### Bug Reports
> 
> **Summary**: When in vim insert mode, hit backspace when the cursor is at the end of a line containing only spaces.
> **Expected Behaviour**: Delete spaces so that the cursor is placed at a multiple of the soft tab width (i.e. multiple of 4 spaces). Essentialy remove a tab stop.
> **Observed Behaviour**: Delete a single space and moves the cursor to the left one position.
> 
> **Summary**: When in vim insert mode, hit Ctrl-D when the cursor is at the end of a line containing only spaces.
> **Expected Behaviour**: Delete spaces so that the cursor is placed at a multiple of the soft tab width (i.e. multiple of 4 spaces). Essential remove a tab stop.
> **Observed Behaviour**: Deletes all spaces in the line.
> 
> The workaround at the moment is to reason about how many spaces I have to delete and then smash the backspace key to get rid of that may spaces. My typical muscle memory of vim is to be in a line, want to add things after it, hit o then backspace until I'm at the right indentation, then start typing.
> 
> When in normal editor mode (non vim mode) backspacing does what's expected and deletes 4-space tabs.
> 
> Cheers,
> James

@mightyguava is this something you could change easily? I took a cursory look at vim.js but it's tricky for me to figure out how that all works.

**Comment by marijnh** [comment]
No one is maintaining the vim mode at the moment, so you're probably on your own when it comes to fixing this.

**Comment by marijnh** [comment]
The vim code is now being maintained at https://github.com/replit/codemirror-vim/ . If this is still important, check whether there is an issue open for it there.
