### ISSUE TITLE
Cursor invisible in Vim mode when visually selecting paragraphs

### ISSUE THREAD

**Issue by guidebin** [codemirror/codemirror5#4067]
Reproducible on http://codemirror.net/demo/vim.html

When you enter visual mode and select an inner paragraph(vip) it works, but when you select around a paragraph (vap), it selects the right characters but the cursor is invisible. The cursor should show on the first empty line below the selected paragraph.

**Comment by marijnh** [comment]
The vim code is now being maintained at https://github.com/replit/codemirror-vim/ . If this is still important, check whether there is an issue open for it there.
