### ISSUE TITLE
all the line is indented when tab is pressed

### ISSUE THREAD

**Issue by bgultekin** [codemirror/codemirror5#423]
hi,

when i press tab after some text in codemirror editor, the text is also indented. i looked for if it is option or not, but i couldn't find anything. i attached a image to explain clearly.

i tried it demos in your website and on chrome, ie, ff (latest versions). 
image: http://www.freeimagehosting.net/newuploads/yxnwp.jpg

**Comment by nishantsharma13903** [comment]
I thanks to both of you
