### ISSUE TITLE
vim paragraph text object handles whitespace incorrectly

### ISSUE THREAD

**Issue by brandonbloom** [codemirror/codemirror5#4407]
Try `vap` or `vip` to select a paragraph (block of code) surrounded by "blank" lines. If the blank lines have whitespace on them, vim still treats them as paragraph separators. However, CodeMirror's vim bindings treat whitespace-only lines as part of the paragraph. `vap` should work differently in that it should select the whitespace of the trailing paragraph separator where `vip` should select only the non-whitespace content of the paragraph.

**Comment by nightwing** [comment]
Do you know why `p` text object is inconsistent with behavior of `{` and  `}`?
In Ace i have changed [`function isEmpty(i) { return !cm.getLine(i); }`](https://github.com/codemirror/CodeMirror/blob/0d296633aa4f297741a09ad8efa031589f6b2d9c/keymap/vim.js#L3432) to [ function isEmpty(i) { return !/\S/.test(cm.getLine(i)); }](https://github.com/ajaxorg/ace/blob/5b52446725f8886d42ae636057d35ffa91b1a204/lib/ace/keyboard/vim.js#L4234 ), but that changes the behavior of `{` as well.

**Comment by brandonbloom** [comment]
Note sure, but for what it's worth, this is from `:help paragraph`:

```
							*paragraph*
A paragraph begins after each empty line, and also at each of a set of
paragraph macros, specified by the pairs of characters in the 'paragraphs'
option.  The default is "IPLPPPQPP TPHPLIPpLpItpplpipbp", which corresponds to
the macros ".IP", ".LP", etc.  (These are nroff macros, so the dot must be in
the first column).  A section boundary is also a paragraph boundary.
Note that a blank line (only containing white space) is NOT a paragraph
boundary.
Also note that this does not include a '{' or '}' in the first column.  When
the '{' flag is in 'cpoptions' then '{' in the first column is used as a
paragraph boundary |posix|.
```

And this is a little down from `:help text-objects`:

```
							*v_ap* *ap*
ap			"a paragraph", select [count] paragraphs (see
			|paragraph|).
			Exception: a blank line (only containing white space)
			is also a paragraph boundary.
			When used in Visual mode it is made linewise.
```

**Comment by marijnh** [comment]
The vim code is now being maintained at https://github.com/replit/codemirror-vim/ . If this is still important, check whether there is an issue open for it there.
