### ISSUE TITLE
Vim mode: '*' motion doesn't work in visual line select mode

### ISSUE THREAD

**Issue by lbobryan** [codemirror/codemirror5#4821]
Repro:
1. Open any file and enable Vim keybindings.
2. Enter visual line select mode through "shift-v"
3. Hit the * character

Expected:
The cursor should go to the next instance of the word under the cursor.

Actual: 
The cursor doesn't move.

**Comment by drop** [comment]
'#' symbol is not work in visual line mode. Also 'n' and 'shift-n' is unpredictable in this case.

**Comment by marijnh** [comment]
The vim code is now being maintained at https://github.com/replit/codemirror-vim/ . If this is still important, check whether there is an issue open for it there.
