### ISSUE TITLE
onChange should only be called for user input

### ISSUE THREAD

**Issue by chriscalo** [codemirror/codemirror5#485]
It breaks convention that onChange is called both for user input and for programmatic changes (such as calling setValue). Everywhere else in HTML controls, change events fire only for user input, not when the page author changes a value.

The real issue is that I need to be able to distinguish between when I update the content and when the user does. I could keep track of this, but then I feel like I'm patching something that's broken. In my opinion, this logic belongs in the editor. I see several solutions:
1. Only call onChange for user input.
2. Add a parameter to setValue that says whether onChange should be called.
3. Add a property to an event object passed to onChange that indicates whether the change was in response to user input.

**Comment by Glench** [comment]
if anyone else finds this like I did, you can now look at `change.origin` to distinguish between programmatic and user input
