### ISSUE TITLE
Double Paste Issues In Chrome

### ISSUE THREAD

**Issue by AugmentBLU** [codemirror/codemirror5#528]
Hello,

I have been using CodeMirror in MODX CMS and when copy pasting text in to an area that uses CodeMirror, it seems to double paste the text.  I only use Chrome so I can only say it happens in this browser but it has happened in numerous versions of CodeMirror and MODX.

I do not think it's anything to do with MODX but I could be wrong.  The MODX Manager uses ExtJS where I am using CodeMirror to edit PHP or HTML code so could there be a conflict? The console shows no errors though which is odd.  Is there a known issue with double pastes in Chrome?  

Another issue is, when the double paste happens I cannot type or use the arrows on my keyboard.  Instead I have to use the mouse to highlight the double paste and then delete.

If there's any further info I can provide, let me know.

Thanks

**Comment by drenther** [comment]
https://github.com/andrebnassis/codemirror-readonly-ranges/issues/6
Double paste issue happening when this extension is enabled. Not sure if it is due to how the package tries to handle paste or due to an upstream issue in codemirror.
