### ISSUE TITLE
Cursor moves past end of line in vim

### ISSUE THREAD

**Issue by nakulj** [codemirror/codemirror5#5422]
## To reproduce
- Open the [vim demo](http://codemirror.net/demo/vim.html).
- Enter `normal` mode.
- Click past the end of a line.

## Expected
Cursor should be over the last character in the line.
![expected](https://user-images.githubusercontent.com/3213360/40443856-6e381020-5e7c-11e8-9de1-56fede99c6b9.png)

## Actual
Cursor moves past the last character in the line.
![actual](https://user-images.githubusercontent.com/3213360/40443903-93eccc0c-5e7c-11e8-8374-2dd4d0d959e9.png)
Interestingly, if you move the cursor left, it goes to the correct position, and then it can't be moved right again, so it looks like CodeMirror already knows that this is an illegal position.

I'd like to help with a pull request, but I'm not sure where to start- any pointers would be appreciated :)

**Comment by marijnh** [comment]
The vim code is now being maintained at https://github.com/replit/codemirror-vim/ . If this is still important, check whether there is an issue open for it there.
