### ISSUE TITLE
Implement sentence text object operations

### ISSUE THREAD

**Issue by joelostblom** [codemirror/codemirror5#5454]
It would be useful to be able to operate on sentences as text objects with operations like `das`, `cis`, etc. I believe most of the work for implementing sentence text objects has been done in #5353 which added functions to find sentences and move over them with `(` and `)`.

I tried dabbling around a bit myself, but I have never used javascript before so I can only offer a simple solution: Inserting the snippet below after [line 1958](https://github.com/codemirror/CodeMirror/blob/master/keymap/vim.js#L1958) works.

```js
        } else if (character === 's') {
          /* adjust head to account for the movement of `findSentence()` when
          the starting position is on the period at the end of the sentence
          or the space between sentences*/
          head.ch = head.ch + 2;
          var sent_beg = findSentence(cm, head, motionArgs.repeat, -1);
          if (inclusive) {
            tmp = {
                start: sent_beg,
                end: findSentence(cm, sent_beg, motionArgs.repeat, 1)
            };
          } else {
            tmp = {
                start: sent_beg,
                end: findSentence(cm, sent_beg, motionArgs.repeat, 1)
            };
              tmp.end.ch = tmp.end.ch - 1
          }

```

I suspect someone wants to write a proper solution where `findSentence()` takes an `inclusive` argument just like `findParagraph()`. If that's not the case, I can PR this, since it at least works as expected (in my limited testing).

**Comment by chrisgrieser** [comment]
Just want to add that I would also love to have that functionality. I am an Obsidian user and when writing in Markdown, `is` and `as` are dearly missing. 

My current workaround is to use `nmap X (d)` and `nmap S (c)` via the [vimrc plugin](https://obsidian.md/plugins?id=obsidian-vimrc-support),  to emulate `das` and `cis`, which isn't perfect, but somewhat works.

**Comment by kometenstaub** [comment]
I've made a PR to the current repo that hosts the cm6 adapter.
https://github.com/replit/codemirror-vim/pull/19

My first implementation was a bit like yours (without knowing it), but I eventually decided to implement it myself (albeit still based on the findSentence() code).
