### ISSUE TITLE
Vim go to and add new line above/below (o | O) leaves flashing block (includes pr for fix)

### ISSUE THREAD

**Issue by goofiw** [codemirror/codemirror5#5544]
Reproable on the demo site.  I made a pull request that fixes the issue.

[Link to PR](https://github.com/codemirror/CodeMirror/pull/5543/commits/2be7da75a1d0be1413d9ea6bc257d8d147e89c75)

Basically, the runInOp is wrapped around the addNewLineAndIndent function so the new line ends up being created and moved to after we go into insert mode which is muddling things up.  I just wrapped the enterInsertMode function in a timeout to push it to the next run loop so all the operations should have finished.

**Comment by goofiw** [comment]
Update:  previous fix failed some tests (mainly replaying macros didn't work quite right) new pr:
https://github.com/codemirror/CodeMirror/pull/5547

I don't love the solution of moving the 'go to insert mode' into a timeout to push it off to the next run loop, but it works.

**Comment by marijnh** [comment]
The vim code is now being maintained at https://github.com/replit/codemirror-vim/ . If this is still important, check whether there is an issue open for it there.
