### ISSUE TITLE
Monokai theme style bug in Firefox

### ISSUE THREAD

**Issue by neon-dev** [codemirror/codemirror5#5647]
Focusing the editor text field in Firefox 6X.X triggers a strange effect, if you happen to use the Monokai theme: Keywords toggle their font boldness (bold-normal-bold-normal...) in about the same interval as the cursor is blinking. But the blinking of the cursor isn't always synchronous with the boldness effect, so it may not be directly related.
Another funny thing: If you open the developer console and inspect the DOM nodes (re-focusing the editor of course), it suddenly stops. Probably due to the added latency, so it maybe doesn't even happen on weak hardware.
You can reproduce it by visiting https://codemirror.net/demo/theme.html#monokai with a current version of Firefox and clicking inside the text area. I don't know with which FF version this started, but I remember it didn't happen in some previous version.

**Comment by marijnh** [comment]
Not seeing this in FF 63. There's nothing about font weight in the monokai theme, which makes this doubly weird.

**Comment by neon-dev** [comment]
I've updated from FF 63.0 to 63.0.1 today. Just tried the safe mode to see if any addon was responsible, but no change.
Here's a demonstration how it looks on my side:
![monokai](https://user-images.githubusercontent.com/1169307/47866485-2ad80800-ddff-11e8-8104-dc7637f04a04.gif)

**Comment by neon-dev** [comment]
Not experiencing this with current versions anymore, therefore I am closing this issue.
