### ISSUE TITLE
[vim] Substitutions getting multiple entries in history

### ISSUE THREAD

**Issue by heppe** [codemirror/codemirror5#5810]
To undo a substitution, vim keybindings require two undo commands rather than just one.

I spent 1/2 day chasing this, and I think it boils down to something similar to but not quite the same as #[3436](https://github.com/codemirror/CodeMirror/issues/3436).  Vim.js calls replaceRange internally to do its commit after insert mode is finished.

repro steps: in [vim demo](https://codemirror.net/demo/vim.html):
  's', 'a', ESCAPE, 'u'
replaces a single character with an 'a', then attempts to undo.  The state after undo, however, is with the character missing.  It takes an additional 'u' undo command to get it to the proper state.

My search took me to the 'start a new event' [block](https://github.com/codemirror/CodeMirror/blob/ed8dfeb5e2ed25b5dd1f1eccc7b757ca6dbd118d/src/model/history.js#L84) in addChangeToHistory, which 

I noticed that with sublime keybindings, it is possible to select a range and simultaneously delete/replace with a single history entry.  It would be good if we could get vim replacement to behave similarly.

Is there a way to group multiple history entries such that they will be undone together, or should I try to get them to merge, despite their separate origins?

**Comment by marijnh** [comment]
> Is there a way to group multiple history entries such that they will be undone together, or should I try to get them to merge, despite their separate origins?

Wrapping the calls that make the changes in a call to `.operation` should have this effect.

**Comment by marijnh** [comment]
The vim code is now being maintained at https://github.com/replit/codemirror-vim/ . If this is still important, check whether there is an issue open for it there.
