### ISSUE TITLE
[vim] increment/decrement producing NaN, RangeError, other unexpected results

### ISSUE THREAD

**Issue by evanminsk** [codemirror/codemirror5#5887]
in vim mode, incrementing or decrementing numbers like 088, -09, 08, 019 produces NaNs and other unexpected results

steps to reproduce:
type a number with a leading zero containing the digits 8 or 9
ctrl+a or ctrl+x
expected: since number can't be octal, interpreted as decimal number  increments or decrements
actual: various unexpected results such as number replaced with NaN, 008 gets incremented to 001, or in the case of 08 and 09:
```
Uncaught RangeError: Invalid array length
    at Object.incrementNumberToken (vim.js:2763)
    at Object.processAction (vim.js:1341)
    at Object.processCommand (vim.js:1261)
    at vim.js:968
    at runInOp (codemirror.js:3898)
    at CodeMirror.operation (codemirror.js:8594)
    at vim.js:962
    at doHandleBinding (codemirror.js:7118)
    at codemirror.js:7189
    at lookupKey (codemirror.js:6764)
```

**Comment by evanminsk** [comment]
We could add a check for non-octal digits after figuring out the base in incrementNumberToken:
```
var base = {'0b': 2, '0': 8, '': 10, '0x': 16}[baseStr.toLowerCase()];
if (base == 8 && !digits.match(/^[0-7]*$/)) {
  // number has leading zero but contains non-octal digits
  base = 10;
}
var number = parseInt(match[1] + digits, base) + (increment * actionArgs.repeat);
```
This would prevent the NaNs and RangeError exceptions but it's a little weird to use.
For example if you start with 008 and increment repeatedly you would get 009, 010, 011, ..., 017, 020 which is probably not what you wanted and there's not really a good way to go from 017 to 018.

vim has the nrformats option which you can remove octal from if you don't want octal numbers so maybe adding a similar option would be best here?

**Comment by marijnh** [comment]
The vim code is now being maintained at https://github.com/replit/codemirror-vim/ . If this is still important, check whether there is an issue open for it there.
