### ISSUE TITLE
copy / paste of one line will produce one extra <new line>

### ISSUE THREAD

**Issue by soliton4** [codemirror/codemirror5#598]
- go to http://codemirror.net/demo/complete.html
- klick in the editor to activate it
- press home as long as it takes to be at first position of a line.
- press shift + down  to select the complete line
- press ctrl + c  to copy it
- press ctrl + v  to paste it once - > ok
- press ctrl + v  again. -> get a extra new line

this is a usual attempt to duplicate a line. but in addition you will get a new line
this happened first somewhen in the 2.2. line. but also in the actual 2.3

thanks for fixing it.
love your project
matthias

**Comment by xzel23** [comment]
OK, I'm still affected by this, so I bisected it. Last version that did not expose this bug was 4.0. I will try to identify the exact code change now.

**Comment by AllanOricil** [comment]
I noticed this bug today. Anything that I paste on code mirror duplicates :/
