### ISSUE TITLE
 codemirror is empty when inside element with display:none

### ISSUE THREAD

**Issue by frozeman** [codemirror/codemirror5#61]
when i have a textarea which is inside a div with display:none; the codemirror area is empty.

when i set the height of any div inside the codemirror div larger than the height of the codemirror div a scrollbar appears, (but the div is still empty) when i then scroll the conten appears.

i think it have to do with calculated size of the CodeMirror-gutter, which can not be done when its inside a display:none block.

**Comment by onmarx** [comment]
**select the class of '.CodeMirror' and instance the object for refresh when change size**

*For example in my case I want to click a button to add and remove an 'active' class to make the content of CodeMirror appear and disappear.*

    .CodeMirror {
      border-radius: 3px;
      margin: 10px 0 8px;
      padding: 5px;
      width: 100%;
      height: auto;
      display: none;
    }
    
    .CodeMirror.active {
      display: block;
    }

CodeMirror Object 

    const editor = CodeMirror.fromTextArea(textarea,{
        lineNumbers:true,
        tabSize:4,
        theme: 'material',
        mode:"javascript",
        readOnly: true,
      });

Event of btn

        btn.addEventListener('click', showCode)
  
**Solution**

    function showCode () { 
      const editor= document.querySelector('.CodeMirror')
      editor.classList.toggle('active')
      
      // use the object for refresh CodeMirror 
      editor.CodeMirror.refresh()
    }

**Comment by onmarx** [comment]
**select the class of '.CodeMirror' and instance the object for refresh when change size**

*For example in my case I want to click a button to add and remove an 'active' class to make the content of CodeMirror appear and disappear.*

    .CodeMirror {
      border-radius: 3px;
      margin: 10px 0 8px;
      padding: 5px;
      width: 100%;
      height: auto;
      display: none;
    }
    
    .CodeMirror.active {
      display: block;
    }

CodeMirror Object 

    const editor = CodeMirror.fromTextArea(textarea,{
        lineNumbers:true,
        tabSize:4,
        theme: 'material',
        mode:"javascript",
        readOnly: true,
      });

Event of btn

        btn.addEventListener('click', showCode)
  
**Solution**

    function showCode () { 
      const editor= document.querySelector('.CodeMirror')
      editor.classList.toggle('active')
      
      // use the object for refresh CodeMirror 
      editor.CodeMirror.refresh()
    }
