### ISSUE TITLE
[vim][feature request] Implement Ctrl+o in insert mode

### ISSUE THREAD

**Issue by ahirschberg-corp-oss** [codemirror/codemirror5#6224]
Hi,

One feature I use in Vim quite frequently is insert mode `<C-o>`, and I would love to see it implemented in CodeMirror as well. What it does:
When in insert mode:
1. Press `<C-o>`
2. You are now in Normal mode for one command.
3. Enter your desired Normal mode command.
4. You are automatically put back in insert mode.

This is quite useful in certain scenarios. For example (assume `|` represents the cursor):
```python
# in Insert mode
my_meth|od(arg1, arg2, arg3):

# type: <C-o> $
# this takes you out of Insert for one keystroke, and 
# moves the cursor to the end of the line

# back in Insert mode
my_method(arg1, arg2, arg3):|
```

It is quite useful for quickly adjusting the cursor position without needing to leave and re-enter insert mode, though obviously it can be used for much more.

Docs:
`:help i_CTRL-O`, 
or the web mirror [here](https://vimhelp.org/insert.txt.html#insert.txt) (search for `i_CTRL-O`).

**Current CodeMirror behavior** (tested on https://codemirror.net/demo/vim.html)
1. Enter insert mode (`i`)
2. Type `<C-o>`
3. The browser's file menu opens

**Comment by marijnh** [comment]
The vim code is now being maintained at https://github.com/replit/codemirror-vim/ . If this is still important, check whether there is an issue open for it there.
