### ISSUE TITLE
Vim regex capture groups require $ instead of \

### ISSUE THREAD

**Issue by har79** [codemirror/codemirror5#6253]
Steps:
* be in vim mode
* use regex for replace, e.g., `:%s/(a)(lot)/\1 \2/g`

Expected: "alot" is replaced with "a lot" consistent with Vim's behaviour
Actual: replaced with literal "\1 \2"; requires use of `.../$1 $2/g` to get equivalent behaviour

It looks like the replacment of capture groups is done here: https://github.com/codemirror/CodeMirror/blob/master/keymap/vim.js#L4899

Matching either '$' or '\' could be a good option to preserve existing behaviour for anyone used to it.

Thanks!

**Comment by marijnh** [comment]
The vim code is now being maintained at https://github.com/replit/codemirror-vim/ . If this is still important, check whether there is an issue open for it there.
