### ISSUE TITLE
[Bug] Vim mode + contenteditable doesn't show any caret if content is empty

### ISSUE THREAD

**Issue by thien-do** [codemirror/codemirror5#6393]
Reproduce: go to https://codemirror.net/demo/vim.html and delete all content
Expectation: the fat caret is still shown at the first character position
Actual: no caret is shown

Note:
- If inputStyle is "textarea" instead then the caret is shown even if content is empty
- Related: https://github.com/codemirror/CodeMirror/issues/3552

**Comment by ppasupat** [comment]
Possibly related: #6312

When `inputStyle` is "contenteditable", the vim keymap displays the normal mode cursor (fat cursor) by using `doc.markText` to mark the current character. An empty line does not have any character, so the mark does not show up.
