### ISSUE TITLE
Vim mode ignores `rtlMoveVisually`

### ISSUE THREAD

**Issue by esm7** [codemirror/codemirror5#6574]
When CodeMirror is set to RTL, and `rtlMoveVisually` is set (the default on most platforms), the cursor in Vim Normal mode misbehaves.
Standing on an RTL text (e.g. Hebrew characters) and pressing <Left>/<Right>/j/k moves to the wrong side.
Seems like in `vim.js` the `moveByCharacters` function is just unaware of this setting and always moves logically.

**Comment by marijnh** [comment]
I think it could be argued that this is true to vim's own behavior, but I don't know a lot about vim's bidi support.

**Comment by esm7** [comment]
Vim by itself takes a very different approach to BIDI which is not in-line with any modern editor. So there's no real reference here to look up to.
But with the current behavior, when CodeMirror is set to RTL with Vim key bindings, pressing <Left> in insert mode will work as expected (goes left on the screen), and when in normal mode the very same <Left> key goes right. I think that's an inconsistent user experience, and having the keys in normal mode respect `rtlMoveVisually` sounds to me like the most straight-forward way to fix it.

**Comment by marijnh** [comment]
That makes sense. If you want to submit a pull request that makes normal mode consistent with insert mode that'd be welcome.

**Comment by marijnh** [comment]
The vim code is now being maintained at https://github.com/replit/codemirror-vim/ . If this is still important, check whether there is an issue open for it there.
