### ISSUE TITLE
isUpperCase and isLowerCase tests for vim mode are ascii-only

### ISSUE THREAD

**Issue by berekuk** [codemirror/codemirror5#6660]
https://github.com/codemirror/CodeMirror/blob/dc3952a60b6cf8ea7b2cb66521ae5165a04d444e/keymap/vim.js#L427-L429

This causes some vim commands, e.g. `~` key (case switching) to work incorrectly.

Steps to reproduce:
1. Enable Vim mode.
2. Enter some text in mixed case in cyrillic, e.g. “строчные ЗАГЛАВНЫЕ”.
3. Move cursor to the first letter and press “~” a few times.
4. Notice that smallcase letters turn into uppercase, but uppercase letters don’t change.

**Comment by calister123** [comment]
``
<script type="text/javascript">
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/60becceedd60a20abbe51f53/default';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>

**Comment by meleu** [comment]
I confirm this issue is happening even for English text (not limited to Cyrillic).

Note: my system's language is configured to Portuguese-Brazil, but I usually write in English.

**Comment by marijnh** [comment]
The vim code is now being maintained at https://github.com/replit/codemirror-vim/ . If this is still important, check whether there is an issue open for it there.
