### ISSUE TITLE
Nmap doesn't send all the keys

### ISSUE THREAD

**Issue by filyp** [codemirror/codemirror5#6695]
I'm using vim mode in Obsidian, which automatically formats edited text as markdown.
I wanted to remap
```
nmap o A<Enter>
```
so that pressing `o` in some list would continue the list, but it turns out that after insert mode is entered (after `A`) no more keypresses are sent, so the `<Enter>` won't have any effect. Tried it with other things than `<Enter>`  and anything after `A` doesn't have effect.

Is there some fix or workaround?

**Comment by benhormann** [comment]
It is a known limitation, so better to ask on the Obsidian forum. Try [this plugin](https://github.com/esm7/obsidian-vimrc-support), maybe there's an `obcommand` that helps.

A workaround is going to depend on how they detect <kbd>Enter</kbd>. It might be `keypress` or `input` event, which you can try construct and dispatch. Or maybe they have an API you can call directly?
Then use `defineAction` and `mapCommand` to map to <kbd>o</kbd>, with `handleKey` to get into insert mode. See [Vim Mode API](https://codemirror.net/doc/manual.html#vimapi) in the manual.

Another option is to do your own auto formatting, using CodeMirror's API.

**Comment by marijnh** [comment]
The vim code is now being maintained at https://github.com/replit/codemirror-vim/ . If this is still important, check whether there is an issue open for it there.
