### ISSUE TITLE
Session-level persistence for :hlsearch setting

### ISSUE THREAD

**Issue by MattSPalmer** [codemirror/codemirror5#6743]
Reproduced via [this online demo](https://codemirror.net/demo/vim.html) in Chrome 91 on MacOS, as well as the latest release of the [Obsidian app](https://obsidian.md).

### Description

When searching with native Vim, the highlighting of search matches is determined by the state of the internal variable `hlsearch`. This variable (on by default) persists until vim is closed, unless modified directly.

However, CodeMirror behaves differently, in that changes to the `hlsearch` (via running `:nohl`) setting only stick around as long as the current search query. Once you search for something new, the variable seems to reset, requiring someone who doesn’t want highlights to run `:nohl` everytime they do a new search.

### Proposed solution

Match the behavior of native Vim by persisting changes to Vim “variables” like hlsearch.

### Current workaround

`/,,<Enter>`

A costly workaround since we’re trading the persistence of the highlight setting for the persistence of the search query.

**Comment by benhormann** [comment]
`:nohls` doesn't change `'hlsearch'`

> `:noh[lsearch]`
> Stop the highlighting for the 'hlsearch' option. It is automatically turned back on when using a search command, or setting the 'hlsearch' option.

It's the `'hlsearch'` option, `:set nohls`, that is missing. How about an option to clear the highlight after movement, like [vim-cool](https://github.com/romainl/vim-cool)?

For a better workaround, try `:map <C-l> :nohls`.

**Comment by marijnh** [comment]
The vim code is now being maintained at https://github.com/replit/codemirror-vim/ . If this is still important, check whether there is an issue open for it there.
