### ISSUE TITLE
Tilde key does not function on UK keyboard layout

### ISSUE THREAD

**Issue by seatrout** [codemirror/codemirror5#6771]
Using a UK British English keyboard layout, where the tilde symbol (~) is located as the capital hash (#), next to the return key, the tilde is not detected at all using the vim keymap:

**Steps to reproduce**
- switch to a UK English keyboard layout
- using CodeMirror in vim mode, type a tilde character 

**Expected Behaviour**
- in Insert mode: a tilde character is typed
- in Normal mode: the case of the character under the cursor is changed

**Actual behaviour**
- Nothing happens.
- The tilde character can still be registered using the Windows shortcut [Alt]126 on the numeric keypad. Then it works as expected, in both modes.

**Comment by seatrout** [comment]
Note: this only happens in Vim Mode.

**Comment by alialmagikoq** [comment]
`

**Comment by alialmagikoq** [comment]
### 

> _**DEAD!COD**_

**Comment by alialmagikoq** [comment]
@marijnh [https://github.com/codemirror/CodeMirror/issues/6771](url)

**Comment by marijnh** [comment]
The vim code is now being maintained at https://github.com/replit/codemirror-vim/ . If this is still important, check whether there is an issue open for it there.
