### ISSUE TITLE
Vim mode: exiting replace mode with 2-char mapping for <Esc> deletes char after cursor

### ISSUE THREAD

**Issue by bmccutchon** [codemirror/codemirror5#6836]
Steps to reproduce:

1. Go to the editor here: https://codemirror.net/demo/vim.html.
2. Replace the editor contents with "getchar".
3. Put cursor on the first character, "g".
4. Run `:imap jk <Esc>`.
5. Type `Rsjk`.

Expected behavior: It should be equivalent to `Rs<Esc>`. The resulting editor contents should be "setchar".

Actual behavior: when typing `jk`, it does exit replace mode as expected, but the character after the cursor ("e") is deleted, resulting in the editor contents `stchar`.

Browser: Chrome on macOS.

**Comment by benhormann** [comment]
When you press <kbd>j</kbd> the "e" gets replaced with "j", then <kbd>k</kbd> deletes the "j". So we can't just check `if (!cm.state.overwrite)` before the delete.

Other notes: The inserted keys are recorded, but the overwritten content is not. The delete happens in `handleKeyInsertMode`, see [vim.js](https://github.com/codemirror/CodeMirror/blob/5.64.0/keymap/vim.js#L910).

**Comment by Testare** [comment]
Using obsidian (which uses codemirror), sometimes plugins will select text while I'm in insert mode, and this same bug occurs: If I use a 2-character escape sequence, it will delete the selected text.

**Comment by marijnh** [comment]
The vim code is now being maintained at https://github.com/replit/codemirror-vim/ . If this is still important, check whether there is an issue open for it there.
