### ISSUE TITLE
Return does not go to next line in normal mode

### ISSUE THREAD

**Issue by hawkiboy** [codemirror/codemirror5#6856]
In most vim environments you can hit the return key in normal mode and will go to the next line. In the Obsidian vim plugin environment hitting return does absolutely nothing, as far as I can see.

**Comment by WhiteNoiseDev** [comment]
This is Obsidian's problem not Codemirror's.

**Comment by huyz** [comment]
In any case, for me hitting the return key in normal mode does as expected.
(Obsidian v0.14.15 + a million plugins)

**Comment by marijnh** [comment]
The vim code is now being maintained at https://github.com/replit/codemirror-vim/ . If this is still important, check whether there is an issue open for it there.
