### ISSUE TITLE
Unexpected text deletion on selection related to dead keys

### ISSUE THREAD

**Issue by silverwind** [codemirror/codemirror5#6893]
On macOS with Browsers Firefox 99 or Safari 15 (but not in Chrome 99), there is a bug where Codemirror unexpectedly deletes content when accent characters like ``` ` ``` are present and when the current keyboard layout has that key as a [dead key](https://en.wikipedia.org/wiki/Dead_key). Disabling the dead key in the keyboard layout eliminates the issue.

Here's an example of entering a text with backtick characters and then using the mouse to select the content via a drag action:

![simple2](https://user-images.githubusercontent.com/115237/157456692-3377c865-cd63-4200-9cec-9cb8f452dcbb.gif)

For comparison, a regular `<textarea>` does not show such issues:

![simple3](https://user-images.githubusercontent.com/115237/157457062-1eace384-30ff-4da8-b3d6-92a2b0b42ede.gif)

**Comment by silverwind** [comment]
What's interesting is that the problem completely goes away after installing a keyboard layout that eliminates [dead keys](https://en.wikipedia.org/wiki/Dead_key), for example [this one](https://github.com/sebroeder/osx-keyboard-layout-german-no-deadkeys).

**Comment by marijnh** [comment]
Attached patch seems to help with this.
