### ISSUE TITLE
Missing codemirror.js file on the website

### ISSUE THREAD

**Issue by kostya9** [codemirror/codemirror5#6931]
We used the file 'https://codemirror.net/lib/codemirror.js' in our app, and it is now missing. Is this intentional? 

I found that https://codemirror.net/5/lib/codemirror.js works fine, maybe some kind of redirect could help alleviate this issue (if this is intentional)?

**Comment by marijnh** [comment]
This is called 'hotlinking' of scripts, and it is a _very_ bad idea (it gives me full control over your website, by pulling in a script I'm hosting, and wastes my bandwidth for your visitors). Host your own copy of this file, please.
