### ISSUE TITLE
sql-hint with table columns cannot filter columns

### ISSUE THREAD

**Issue by yinyihui** [codemirror/codemirror5#6933]
Codemirror Version: 5.65.4
I try the sql-hint table option and define table columns. When i input . and codemirror hint the columns correctly, but next word triggers the keywords hint not filter the columns.
![图片](https://user-images.githubusercontent.com/13214503/172751189-e2f6c9dc-ed65-4816-8ba0-435f4d3b3716.png)
![图片](https://user-images.githubusercontent.com/13214503/172751247-93254869-3680-448b-91e7-8c042bed3e76.png)
https://github.com/codemirror/codemirror5/blob/7f488eb5c12d71ea7ea75e286b7b9c029453a298/addon/hint/sql-hint.js#L267
I find the code here and it should detect that whether the input word is behind the dot(.), then to match the table columns which is on the left.

**Comment by yinyihui** [comment]
As long time no relpy, I tried myself to change the source code and it works well. Just add the code after the popup checker, it can works correctly.
Origin: [https://github.com/codemirror/codemirror5/blob/7f488eb5c12d71ea7ea75e286b7b9c029453a298/addon/hint/sql-hint.js#L275](url)
`if (search.charAt(0) == "." || search.charAt(0) == identifierQuote) {`
After change: 
`if (search.charAt(0) == "." || search.charAt(0) == identifierQuote || editor.getTokenAt(Pos(cur.line, token.start)).string == "."|| editor.getTokenAt(Pos(cur.line, token.start)).string == identifierQuote) {`

**Comment by marijnh** [comment]
I don't see this issue happening. When I type `a.I`, the SQL mode makes `.I` a single token, so the check at that line succeeds and `nameCompletion` is called.

**Comment by marijnh** [comment]
Yes, I did. Set up an example script that shows the issue if you want me to look into this.

**Comment by yinyihui** [comment]
Set the configuration as follows:
` {
    tabSize: 2,
    mode: "sql",
    theme: "lucario",
    lineNumbers: true,
    autoCloseBrackets: true,
    singleCursorHeightPerLine: false,
    hintOptions: {
      completeSingle: false,
      tables: {
        a: ["ID", "BOND_ID", "PARTY_ID"]
      }
    }
  }`,
As these settings works, then type "a.", the columns pop up correctly. Continue typing the word "I", the hint dose not filter from the columns but show the sql keywords and other builtins, such as  "IN, INSERT".

**Comment by marijnh** [comment]
Ah, there was some weird feature in the SQL mode that turned off tokenizing of dot-prefixed identifiers unless explicitly enabled, and using `"sql"` as mode (rather than a specific dialect) didn't turn that on. Patch d122e55c4818ef72e45939c4c06301bc36cb4a53 should fix that.

**Comment by yinyihui** [comment]
Thanks for the works, and best wishes!
