### ISSUE TITLE
JavaScript mode have problem parsing PegJS mode source code

### ISSUE THREAD

**Issue by jcubic** [codemirror/codemirror5#6934]
I've created CM with JavaScript mode and opened the PegJS mode file, so I can try to fix it, and it's easier to do that in the application.

This is the result:

![JS_mode](https://user-images.githubusercontent.com/280241/173074861-4f409593-4f99-4587-ae75-ba381f5e9878.png)

The rest of the file is ok.

**Comment by marijnh** [comment]
This isn't what I'm seeing when I paste the contents of pegjs.js into [https://codemirror.net/5/mode/javascript/](https://codemirror.net/5/mode/javascript/)

**Comment by jcubic** [comment]
Maybe it's just a temporary glitch but the library was in a bad state somehow.

**Comment by marijnh** [comment]
Well, let me know if you can reliably reproduce it.
