### ISSUE TITLE
Vim mode: using `J` more than once shouldn't add more than one trailing space

### ISSUE THREAD

**Issue by borisv-stripe** [codemirror/codemirror5#6948]
To reproduce, enter this text (there's spaces on each empty line)

```none
  st
    
    
    
    
    atic int n = 0;
```

move the cursor to the first line and hit `J` until both lines are on the same line. This is what I see on https://codemirror.net/5/demo/vim.html 

```none
  st     atic int n = 0;
```

this is what I see in neovim

```none
  st atic int n = 0;
```

**Comment by marijnh** [comment]
The vim code is now being maintained at https://github.com/replit/codemirror-vim/ . If this is still important, check whether there is an issue open for it there.
