### ISSUE TITLE
Can't add dot "." symbol to keybind

### ISSUE THREAD

**Issue by ArztKlein** [codemirror/codemirror5#6950]
I used both . and also Period, and even Dot. None of them works
```js
cm.setOption('extraKeys', {
   'Ctrl-.': 'toggleComment'
});
```
When I changed the . to other characters (eg 'A'), it worked as expected. So the problem is the dot.

Tested in chrome, edge, and using version 5.62.

**Comment by marijnh** [comment]
It may be that your OS or browser is capturing ctrl-. presses? On mine (Linux) they start some kind of input composition that I wasn't aware of before, and also aren't delivered to the page script.

**Comment by ArztKlein** [comment]
Just figured it out. My adblocker extension is being toggled for ctrl+.
