### ISSUE TITLE
Firefox Ubunutu: Editor does not intercept Ctrl-Q

### ISSUE THREAD

**Issue by erosman** [codemirror/codemirror5#6958]
Firefox Nightly 104.0a1 (2022-07-10) (64-bit)
Ubuntu 22.04
FireMonkey Addon

On Windows, I have been using Ctrl-Q to 'toggleComment' but on Ubuntu, Ctrl-Q is not intercepted and instead picked up by Firefox to quit.

```js
  extraKeys: {
    'Ctrl-Q': 'toggleComment',
    'Ctrl-Space': 'autocomplete',
    ...
  }
```

![image](https://user-images.githubusercontent.com/6458876/178218502-c8cb95bb-5eab-4a9a-9f06-3380a716d02c.png)

**Comment by marijnh** [comment]
Yes, I recently noticed this too. Seems to be a new thing Firefox does. Not something a script can do anything about, though.
