### ISSUE TITLE
Personalized display autoComplete 

### ISSUE THREAD

**Issue by Danyqueen** [codemirror/codemirror5#6963]
On Windows, I want to have autocomplete that can be personalized like this
![image](https://user-images.githubusercontent.com/31559302/179479486-0d4c1e79-772b-44ee-8272-1d3e427e122a.png)

But，I can only show hint like this
![image](https://user-images.githubusercontent.com/31559302/179479611-847ab161-4f6f-4e2c-8610-897146b94ceb.png)

I can not have the prefix icon.

[I have read this document](https://codemirror.net/examples/autocompletion/)，but I can't use it，it seems in codemirror6 version，how can I use it in codemirror5 ?

**Comment by marijnh** [comment]
Version 5's autocompletion doesn't have support for icons, but you could use the `render` property on completions to draw them in a custom way.

**Comment by Danyqueen** [comment]
> completions

Thank you! Is there any example？
