### ISSUE TITLE
Please add GDScript support

### ISSUE THREAD

**Issue by Leroy-X** [codemirror/codemirror5#6966]
Hi, Please add GDScript support, thanks

GDScript is a high-level, dynamically typed programming language used to create content. It uses a syntax similar to [Python](https://en.wikipedia.org/wiki/Python_%28programming_language%29) (blocks are indent-based and many keywords are similar). Its goal is to be optimized for and tightly integrated with Godot Engine, allowing great flexibility for content creation and integration.

https://godotengine.org/

**Comment by marijnh** [comment]
We're not adding support for more languages, but it is possible to implement languages in external code (and even to distribute the code over npm).

**Comment by ivanskodje** [comment]
> We're not adding support for more languages, but it is possible to implement languages in external code (and even to distribute the code over npm).

That is an terrible attitude for an open source project with 800+ contributors.

**Comment by ivanskodje** [comment]
> We're not adding support for more languages, but it is possible to implement languages in external code (and even to distribute the code over npm).

That seems like a strange stance for an open source project with over 800 contributors. If there is a good reason behind it, it would be helpful to explain. Right now, it just comes across as dismissive.
