### ISSUE TITLE
Multiple cursor on Alt-Click instead of Ctrl-Click

### ISSUE THREAD

**Issue by abose** [codemirror/codemirror5#6972]
Hello,

 Currently brackets code editor and the test editor in codemirror website activates multicursor with `ctrl-click` .  

* Can this be remapped to `alt-click` by come config? 

Trying this change as `ctrl-click` is mapped to jump to definition on most editors, so brackets too is moving to that.

Thanks,
Arun.

**Comment by marijnh** [comment]
The [`configureMouse`](https://codemirror.net/5/doc/manual.html#option_configureMouse) option should be able to do this.

**Comment by abose** [comment]
found it!
Thanks for the quick Reply @marijnh 

```js
function _mouseHandlerOverride(cm, repeat, event) {
            return {
                addNew: event.altKey // alt key will init multi cursor instead of ctrl-key
            };
        }

new CodeMirror(container, {
configureMouse: _mouseHandlerOverride
}
```
