### ISSUE TITLE
 IE10 script1047 error cause white screen

### ISSUE THREAD

**Issue by zhouaihua** [codemirror/codemirror5#6976]
version:5.65.7 browser:IE10

![image-20220811154747670](https://user-images.githubusercontent.com/42058638/184088114-6444e5ff-7668-4826-ade8-f25c69baf852.png)
![image-20220811155250588](https://user-images.githubusercontent.com/42058638/184088452-acfad66a-86cf-4a36-b7bc-265a23c38919.png)

may be missing a semicolon ??

**Comment by marijnh** [comment]
Could you translate that error message for me?

**Comment by zhouaihua** [comment]
> Could you translate that error message for me?

In strict mode, function declaration cannot be nested within the statement or block. These statements only appear in the top or appear in the function body directly.

**Comment by marijnh** [comment]
Thanks. Attached patch should help.
