### ISSUE TITLE
怎么在指定位置插入小部件呢？

### ISSUE THREAD

**Issue by leonardo110** [codemirror/codemirror5#6977]
addWidget使用之后总是会跑到上方或者下方，我想就在当前光标处插入dom元素，但是一直没实现，我的版本是^4.0.6，是不是版本太低了的缘故？

**Comment by leonardo110** [comment]
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by marijnh** [comment]
I don't speak chinese and if you can't be bothered to run your text through a translation service, I can't either.

**Comment by leonardo110** [comment]
> 我不会说中文，如果您不愿意通过翻译服务来运行您的文本，我也不能。

How to insert widgets at specified positions? After using addWidget, it always runs to the top or bottom. I want to insert the dom element at the current cursor, but it has not been implemented. My version is ^4.0.6, is it because the version is too low?

**Comment by leonardo110** [comment]
> I don't speak chinese and if you can't be bothered to run your text through a translation service, I can't either.

There is another question, how to make custom keywords highlighted? The found use of screenshots is invalid...
![image](https://user-images.githubusercontent.com/34759738/186561445-a5cb3db8-86cf-4e9c-8ada-426af4ac205c.png)

**Comment by marijnh** [comment]
You may want `setBookmark` with the `widget` option.

In general, this is the issue tracker, and not the place for questions. See [the forum](https://discuss.codemirror.net) for that.
