### ISSUE TITLE
Swift code which follows an inline comment isn’t highlighted

### ISSUE THREAD

**Issue by yakovmanshin** [codemirror/codemirror5#6981]
If a line in a `.swift` file has a `/* … */`-style comment followed by code, the code isn’t highlighted.

CodeMirror v5.60.0, as seen in GitHub Desktop:

![](https://user-images.githubusercontent.com/4648742/188640985-585de9cd-6783-4d93-b7f1-eaf5beaa1edd.png)

Also [reported](https://github.com/desktop/desktop/issues/15238) in the GHD repo.

**Comment by marijnh** [comment]
Attached patch should help.
