### ISSUE TITLE
fromTextArea doen not exist

### ISSUE THREAD

**Issue by Kartik-Fulara** [codemirror/codemirror5#6986]
Property 'fromTextArea' does not exist on type 'typeof import("d:/GitHub/project/coders-park/node_modules/codemirror/dist/index")'.ts(2339)

// Package.json
{
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@emotion/react": "^11.10.4",
    "@emotion/styled": "^11.10.4",
    "@mui/material": "^5.10.5",
    "codemirror": "^6.0.1",
    "core-js-pure": "^3.25.1",
    "next": "latest",
    "react": "18.1.0",
    "react-avatar": "^5.0.3",
    "react-dom": "18.1.0",
    "react-hot-toast": "^2.4.0",
    "tailwind-styled-components": "^2.2.0",
    "uuid": "^9.0.0"
  },
  "devDependencies": {
    "@types/node": "17.0.35",
    "@types/react": "18.0.9",
    "@types/react-dom": "18.0.5",
    "@types/uuid": "^8.3.4",
    "autoprefixer": "^10.4.7",
    "postcss": "^8.4.14",
    "tailwindcss": "^3.1.2",
    "typescript": "4.7.2"
  }
}

// Code
`      

         import React from "react";
         import CodeMirror from "codemirror";
         export const Editor = () => {
         React.useEffect(() => {
             async function init() {
              CodeMirror.fromTextArea(document.getElementById("editor"));
               }
             init();
              } , []);
        return (
         <textarea id="editor" placeholder="Welcome to The Ghost Area"></textarea>
       );
      };
`

**Comment by marijnh** [comment]
This sounds like a TypeScript error, but this library doesn't come with type declarations, so I can't really help you with that. [`@types/codemirror`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/codemirror/index.d.ts) does seem to define `fromTextArea`.
