### ISSUE TITLE
Source diff capability ?

### ISSUE THREAD

**Issue by pkasson** [codemirror/codemirror5#6987]
Is there a way to perform a source code diff, if given two files / bodies of code to compare with each other ?

**Comment by marijnh** [comment]
Do you mean the [merge view](https://codemirror.net/5/demo/merge.html)? Or are you just looking to compute the actual diff? In that case, you'll want to use some other tool.

Anyway, this is the bug tracker, not really the place for asking questions. See [the forum](https://discuss.codemirror.net) for that.

**Comment by pkasson** [comment]
Sorry - yes, looking for a diff capability.  Closing.
