### ISSUE TITLE
the cursor disappear when use basicSetup

### ISSUE THREAD

**Issue by shedan9** [codemirror/codemirror5#6997]
when I use the basic example in vite enviroment，I find the cursor is disappear when use basicSetup. I want know why and how to resolve it.

not use basicSetup:
![image](https://user-images.githubusercontent.com/26622701/198982271-582becb5-6eb8-4861-b53d-0ed22b4bc4c2.png)

use basicSetup:
![image](https://user-images.githubusercontent.com/26622701/198983581-7f426f01-1dab-4c6c-9f80-63ca3539464d.png)
it is strange that the edit is work, I can input or delete words as normal, but just the cursor is disappear!
![image](https://user-images.githubusercontent.com/26622701/198984898-5a00fda0-cd83-45f4-86d2-30ac9c407a5e.png)

this is the code:
```import { basicSetup } from "codemirror";
import { javascript } from "@codemirror/lang-javascript";
import { EditorState } from "@codemirror/state";
import { EditorView, keymap } from "@codemirror/view";
import { defaultKeymap } from "@codemirror/commands";
let startState = EditorState.create({
  doc: code,
  extensions: [
    // basicSetup,
    javascript(),
    keymap.of(defaultKeymap),
  ],
});

  
view = new EditorView({
  state: startState,
  parent: this.$refs.codeContainer,
})
```

this is my project package.json
```
{
  "name": "vue2-code-editor",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview --port 4173"
  },
  "dependencies": {
    "@bairong/bdx-transform": "^0.1.1",
    "@codemirror/basic-setup": "^0.20.0",
    "@codemirror/lang-javascript": "^6.1.1",
    "codemirror": "^6.0.1",
    "pinia": "^2.0.16",
    "vue": "^2.7.7",
    "vue-router": "^3.5.4"
  },
  "devDependencies": {
    "@vitejs/plugin-legacy": "^2.0.0",
    "@vitejs/plugin-vue2": "^1.1.2",
    "terser": "^5.14.2",
    "vite": "^3.0.2"
  }
}
```

**Comment by marijnh** [comment]
This is the wrong repository for CodeMirror 6 issues. But anyway, doing exactly what you're doing there, I do see the cursor. But since it's not a full code example, I suspect you're putting your editor instance in the Vue state, which will screw up any objects it is given, and that might be causing this.

**Comment by shedan9** [comment]
no, I didn't put editor instance in the Vue state, this is the full code:
```
<template>
  <div class="code-mirror">
    <div class="code-container" ref="codeContainer"></div>
    <button @click="handleExec">exec</button>
  </div>
</template>

<script>
import { basicSetup } from "codemirror";
import { javascript } from "@codemirror/lang-javascript";
import { EditorState } from "@codemirror/state";
import { EditorView, keymap } from "@codemirror/view";
import { defaultKeymap } from "@codemirror/commands";

let view = null;

export default {
  name: "CodeMirror",
  mounted() {
    const code = `const target = {
  page: 1,
  size: 20,
  extra: {
    id: '99'
  },
  list: [
    { name: 'a', value: 1 },
    { name: 'b', value: 2 },
    { name: 'c', value: 3 }
  ]
};
`;

    let startState = EditorState.create({
      doc: code,
      extensions: [
        basicSetup,
        javascript(),
        keymap.of(defaultKeymap),
      ],
    })

    view = new EditorView({
      state: startState,
      parent: this.$refs.codeContainer,
    })
  },
  methods: {
    getCode() {
      return view.state.doc.toString();
    },
    handleExec() {
      const fn = new Function(this.getCode());
      fn();
    },
  },
}
</script>
```

**Comment by shedan9** [comment]
I find the cause of this, when use basicSetup, the code have overflow-x, the cursor and selection is in the wrong position, but I don't know why.
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/26622701/199144060-dbabdeda-bf39-4a4f-9c11-694cf7a33bd1.png">
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/26622701/199144156-5a002fa5-2f5b-4a78-99b2-52356f51fcb9.png">

**Comment by shedan9** [comment]
the vue project init css has problem, this is the causing code:
```css
*,
*::before,
*::after {
  position: relative;
}
```
