### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by azhar-siddiqui** [codemirror/codemirror5#7003]
Uncaught TypeError: Cannot read properties of null (reading 'CodeMirror')
    at <anonymous>:7:17

**Comment by marijnh** [comment]
Without more information, this is not something I can say anything about.

**Comment by JHiltunen** [comment]
This also happens to me. Full error message
```
Uncaught TypeError: Cannot read properties of null (reading 'CodeMirror')
    at <anonymous>:7:17
```

Using M1 MacBook Pro and Google Chrome Version 107.0.5304.110 (arm-64).

When I go to any website and then open dev-tools (pressing f12) I can see this error coming every time I press any key on keyboard. This happens only when typing in the browser window. This is not happenning ig i'm writing to developer console

**Comment by marijnh** [comment]
If it happens for any website, you must have some broken extension installed. Disable extensions until it goes away.

**Comment by JHiltunen** [comment]
Turning off extensions one by one solved it!

I had extension called "Blackbox - Select. Copy. Paste & Search" that was causing this error
