### ISSUE TITLE
getting TypeError: Cannot read properties of null (reading 'CodeMirror')

### ISSUE THREAD

**Issue by chaitanya71998** [codemirror/codemirror5#7004]
Greetings,
seems not to be asked here, but we are getting lots of errors like this
```
TypeError: Cannot read properties of null (reading 'CodeMirror')
  at ? (<anonymous>:7:17)
```
We haven't used codemirror in our project but getting reported this issue to sentry from last 24 hours. Did anyone have idea why this TypeError ?

**Comment by marijnh** [comment]
If you don't use CodeMirror, then I guess people are loading broken extensions that try to use it, to get this error? In any case, there's not much I say do about this without a lot more context, so I'm going to close this.

**Comment by chaitanya71998** [comment]
Thanks, @marijnh we will sort it

**Comment by marijnh** [comment]
See also #7003, which indeed points at a browser plugin
