### ISSUE TITLE
`div.CodeMirror-selected` for `bespin`

### ISSUE THREAD

**Issue by stdedos** [codemirror/codemirror5#7018]
Hello there,

I'd like to propose a change for the `div.CodeMirror-selected` selector for `bespin`

Line:
https://github.com/codemirror/codemirror5/blob/34b84359c4ce289086c82c203f66ef74614d8a0d/theme/bespin.css#L12

should become:
```css
background: #595959 !important;
```

or equivalent.

My proposal is an educated guess by looking around the repo, "what looks best", "sticking close to the theme colors", and by the intuition that "there won't be any setting that would get AA(A) a11y score"

_Discussion here: https://github.com/openstyles/stylus/discussions/1538_

**Comment by marijnh** [comment]
Attached patch increases the contrast on this.
