### ISSUE TITLE
readToken has a fixed 10 tries cap

### ISSUE THREAD

**Issue by bandinopla** [codemirror/codemirror5#7023]
https://github.com/codemirror/codemirror5/blob/658bff7c56b7829aeabb8a914be5ca728d8aba0b/src/line/highlight.js#L161

Im currently working on a mode that will return null and expect codemirror to re-call the token function so i can internally try another match. It was working up until i found this... 

I think this cap is unnecesary and should leave it to the developer to decide how many times it will be looped because in my scenario i need to be 10+ times... or at least that value should be taken from the mode's configuration object.

This got me hours of debugging scratching my head putting breaks and logs everywhere... it made no sense at all, things were all working fine but failed with i added an item to an array (that internally was involved in returning null from token)

**Comment by marijnh** [comment]
What is your mode doing that it fails to consume any input in 10 calls? That looks like something that A) should easily be fixable in the mode itself by adding a loop there, and B) is probably going to cause an infinite loop if the editor doesn't cut it off.

**Comment by bandinopla** [comment]
> What is your mode doing that it fails to consume any input in 10 calls? That looks like something that A) should easily be fixable in the mode itself by adding a loop there, and B) is probably going to cause an infinite loop if the editor doesn't cut it off.

yeah i just implemented the loop myself inside of the mode, i was doing something like this (pseudo code):

```javascript
...
token(stream, state) {
    for each (pattern in patterns)
         if( pattern == some particular thing)
                patterns = pattern.childPatterns
                return ; // here i was counting on codemirror to loop back token...
}
...
```

the code failed if "patterns" was for example 12 items long.... and the patter that would match is the 11th and not the first 10...

i fixed this by doing the loop myself (psecudo code)

```javascript
...
myToken( stream, state ) {
    for each (pattern in patterns)
         if( pattern == some particular thing)
                patterns = pattern.childPatterns
                return myToken(stream, state ) ; // loop back....
}
...
token(stream, state) {
    return myToken( stream, state )
}
...
```

**Comment by marijnh** [comment]
Glad you found a solution. Modes failing to advance the stream at all was a common source of infinite loops (and thus browser hangs) in the past. Thus, the library cutting it off at some point is intentional.
