### ISSUE TITLE
Add Security Policy

### ISSUE THREAD

**Issue by gabibguti** [codemirror/codemirror5#7032]
Adding a Security Policy is important to provide guidance on how people can report any potential vulnerabilities while also ensuring awareness of the vulnerabilities disclosure timeframe. This is recommended by [Github](https://docs.github.com/en/code-security/getting-started/securing-your-repository#setting-a-security-policy) and other security tools, such as [Scorecard](https://github.com/ossf/scorecard). If you agree, I can open a PR to suggest a Security Policy!

##### Additional Context
I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

**Comment by marijnh** [comment]
I'd rather not add another boilerplate file to all of my repositories. There's a maintainer email listed in package.json, and fortunately, beyond exponential-running-time regexps, client-side editors written in a memory-safe language run in a sandbox don't produce serious security problems all that often.
