### ISSUE TITLE
Request for onChange Event or Value Change Subscription in react-codemirror-merge

### ISSUE THREAD

**Issue by kwonth211** [codemirror/codemirror5#7039]
I'm currently using react-codemirror-merge and would like to detect onChange events or subscribe to value changes. 
Is there a way to achieve this functionality? Any insight or suggestions on how to implement this would be greatly appreciated. Thanks in advance!

**Comment by marijnh** [comment]
See the editor's [event interface](https://codemirror.net/5/doc/manual.html#events). You can use the `left`, `right`, and `edit` properties of the mere view to get at the editor instances inside of it.
