### ISSUE TITLE
Slight glitch with Java indentation

### ISSUE THREAD

**Issue by gigamonkey** [codemirror/codemirror5#7049]
Hey, I'm working on a book hosted on Runestone which uses Codemirror and I noticed this glitch in how it indents Java code:

## Some things that work

The `|` shows where the cursor ends up after typing the given text with `<enter>` showing where I typed enter.

```
public class Foo {<enter>
    |

public class Foo<enter>
{<enter>
    |

public class Foo extends Bar {<enter>
    |

public class Foo implements Bar {<enter>
    |
```

## A couple that don't work as I'd expect

```
public class Foo extends Bar<enter>
{<enter>
|

public class Foo implements Bar<enter>
{<enter>
|
```

I'd expect the last two cases to also indent to the fourth column like the first three do. Yeah, I know, I don't love the Allman style but this book is for AP Java and the College Board does so we kinda have to go with that.

## And then two that weirdly both "work"

```
public class Foo garbage Bar {<enter>
    |

public class Foo garbage Bar<enter>
{<enter>
    |
```

Is this a bug? It at least seems unfortunate.

**Comment by marijnh** [comment]
Hi Peter. Attached patch should work around this.

**Comment by gigamonkey** [comment]
Fantastic thanks! Is this likely to go out in a new release any time soon so I can just ask the Runestone people to update?

**Comment by marijnh** [comment]
I've tagged 5.65.14

**Comment by gigamonkey** [comment]
Awesome. Thank you.
