### ISSUE TITLE
Groovy language support

### ISSUE THREAD

**Issue by nikitakoliadin** [codemirror/codemirror5#7052]
Hey,

I know that there is a legacy groovy mode, but the highlighting is poor and also I do not understand how to add custom linter for that.

Is there any plans to add official Groovy language package with availability to add linter/autocomplete?

**Comment by marijnh** [comment]
There are no such plans, but I am available ([mail](mailto:marijn@haverbeke.berlin) me) for paid mode implementations if that's something that you have budget for.

**Comment by nikitakoliadin** [comment]
@marijnh Could you please answer one more question: if it would be best for us to contribute (is it possible?) the Groovy Language ourselves (Third-party implementation), or to give up on syntax and linter support in CodeMirror and instead use java for syntax highlighting and our own compiler as a linter?

**Comment by marijnh** [comment]
It is definitely possible to implement and maintain your own language mode. See [here](https://codemirror.net/docs/community/#language) for a list of existing 3rd-party language packages.
