### ISSUE TITLE
YAML infinite recursion error

### ISSUE THREAD

**Issue by ClumsyAdmin** [codemirror/codemirror5#7053]
When saving this particular yaml file as `anything.yml`, it causes the browser window to entirely lock up. Happens on every browser I've tried.

https://pastebin.com/raw/77Vah6mK

![image](https://github.com/codemirror/codemirror5/assets/59402569/721a5295-d437-4da8-acc3-8dff5c05eeb3)

**Comment by ClumsyAdmin** [comment]
Thanks, just was wondering if there's any possibility of a new release? Realize since this is legacy there may not be a new release unless requested

**Comment by marijnh** [comment]
I've tagged a 5.65.15
