### ISSUE TITLE
How to use C, C++, C# and Java in CodeMirror

### ISSUE THREAD

**Issue by Jveshi** [codemirror/codemirror5#7057]
I did not find C, C++, C# and Java files in the mode folder. But I found clike. Can this be adapted for these four languages?
I'm a web developer and I don't really understand the relationship of these four languages (search shows they are clike languages)

**Comment by marijnh** [comment]
Use the MIME types listed [on this page](https://codemirror.net/5/mode/clike/) to enable a specific language configuration of the clike mode.

Next time, ask questions on the [forum](https://discuss.codemirror.net) please, not in the bug tracker.

**Comment by Jveshi** [comment]
> Use the MIME types listed [on this page](https://codemirror.net/5/mode/clike/) to enable a specific language configuration of the clike mode.
> 
> Next time, ask questions on the [forum](https://discuss.codemirror.net) please, not in the bug tracker.

Ok, I see, next time I'll ask in the forum, but this time let's discuss it here.

I don't understand this page
https://codemirror.net/5/mode/clike/index.html

It means that it can be used as usual, can these languages be used by introducing the clike mode file?
Is there anything else that needs to be modified?
```
<script src="lib/codemirror.js"></script>
<link rel="stylesheet" href="lib/codemirror.css">
<script src="mode/clike/clike.js"></script>
<script>
     var myCodeMirror = CodeMirror(document.body, {
         mode:  "clike"
    });
</script>
```

**Comment by marijnh** [comment]
Set `mode` to one of the MIME types at the bottom of that page.

**Comment by Jveshi** [comment]
> Set `mode` to one of the MIME types at the bottom of that page.

If I want to use C++
Is such that:
```
var myCodeMirror = CodeMirror(document.body, {
         mode:  "text/x-c++src"
});
```
Or such that:
```
var myCodeMirror = CodeMirror(document.body, {
         mode:  "clike"
         MIME:  "text/x-c++src"
});
```
