### ISSUE TITLE
missing semicolon in codemirror js ver 5.5.0 

### ISSUE THREAD

**Issue by floss-51nullacht** [codemirror/codemirror5#7062]
Hi,
in https://github.com/codemirror/codemirror5/blob/53faa33ac69598b7495e160824b58ebb8d70fe97/src/util/misc.js#L124 is written `var nonASCIISingleCaseWordChar = [...]ud7af]/` without a trailing semicolon and followed by a function.

In a minified version ist becomes ` ... ]/function ...` wich ends in an error.
Best

**Comment by marijnh** [comment]
> In a minified version ist becomes  ... ]/function ... wich ends in an error.

Only if the minifier is broken. If the file we distribute runs, I don't consider this an issue in CodeMirror.
