### ISSUE TITLE
Add syntax highlighting / mode for Splunk (SPL)

### ISSUE THREAD

**Issue by chadbaldwin** [codemirror/codemirror5#7063]
Hopefully this is the right place to go. I'm an avid user of PasteBin, which appears to use codemirror. I noticed that Splunk / SPL is not currently a supported language mode, so thought I would give it a shot and put a request in here in hopes it could eventually show up as an option within PasteBin.

In case it helps, it appears someone created an SPL definition for highlight JS. I figured I would include it here, maybe it will help with creating a definition in codemirror's system format:

https://github.com/swsoyee/highlightjs-spl

Edit: Huh, I guess Slack uses codemirror as well, so it'd be awesome to see Splunk/SPL formatting available there one day as well 😁

**Comment by marijnh** [comment]
No new modes are added or accepted in this project. The recommended way to build/distribute them is as a separate package.
