### ISSUE TITLE
Reference actions by commit SHA

### ISSUE THREAD

**Issue by gabibguti** [codemirror/codemirror5#7064]
Referencing actions by commit SHA in GitHub workflows guarantees you are using an immutable version. Actions referenced by tags and branches are more vulnerable to attacks, such as the tag being moved to a malicious commit or a malicious commit being pushed to the branch.

Although there are pros and cons for each reference, GitHub understands [using commit SHAs is more reliable](https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions#using-shas), as does [Scorecard](https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies) security tool.

This is considered a security good-practice. Plus, we can take this moment to also upgrade `actions/checkout` and `actions/cache`. If you agree, this would change, for example, `actions/checkout@v1` to `actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac` followed by a comment `# v4.0.0` to keep the version readable. If you'd like, I can open a PR.

##### Additional Context

Hi! I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

**Comment by marijnh** [comment]
Sure, a PR would be welcome.
