### ISSUE TITLE
Enforce tests to pass before merging

### ISSUE THREAD

**Issue by gabibguti** [codemirror/codemirror5#7066]
Hey! Have you already considered enforcing tests to pass before merging?

Seems that not all PRs run `ci.yml` before merging. Even if `ci.yml` is configured to run on PRs, workflows by default need to be approved to run for first-time contributors.

If it's a matter of forgetting to run the tests, we can setup a Branch Protection with "Require status checks" and add `build-and-test` (the job that runs the tests in `ci.yml`) to be required for merging.

If the approval step is what's blocking us from running tests before merging, then we can additionally [change the "Fork pull request workflows from outside collaborators" Action setting to "Require approval for first-time contributors who are new to GitHub"](https://github.com/codemirror/codemirror5/settings/actions). Since the workflow runs with minimum permissions, don't use any other critical credentials and does not have dangerous patterns, the outside contributors are not able to attack through this workflow.

Does it make sense to change the settings to enforce tests on PRs?

##### Additional context

Hi again! I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

**Comment by marijnh** [comment]
No. Thanks.
