### ISSUE TITLE
closed root shadow dom support proposal

### ISSUE THREAD

**Issue by pavelfeldman** [codemirror/codemirror5#7074]
Codemirror5 currently does not work in a closed shadow root. A fix like [this](https://gist.github.com/pavelfeldman/84b7836f24301eb07a560d384e05780c) would make it work. Would you be interested in a PR? [getRootNode()](https://developer.mozilla.org/en-US/docs/Web/API/Node/getRootNode) exists in all modern browsers for years now, not sure how much of a compatibility impact it is for cm5 deployment.

**Comment by marijnh** [comment]
CodeMirror also targets old browsers, so this would have to be wrapped in a helper function with a fallback.

Also, did you test on Safari? That browser still has rather broken selection management in shadow DOM.

**Comment by pavelfeldman** [comment]
> CodeMirror also targets old browsers, so this would have to be wrapped in a helper function with a fallback.

Sounds good

> Also, did you test on Safari? That browser still has rather broken selection management in shadow DOM.

I did not, but I will.

I'll read it as a potential interest.
