### ISSUE TITLE
Syntax highlighting for GDScript

### ISSUE THREAD

**Issue by TobiZog** [codemirror/codemirror5#7090]
Hello developers,

could you please add syntax highlighting support for GDScript? 

Official language reference: https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html

Thank you for your great work.

**Comment by marijnh** [comment]
We aren't adding new languages to the distribution. If you need such support, you'll have to build it yourself and distribute it separately.
