### ISSUE TITLE
Can you provide the function of indenting lines in the code, just like vscode? Thank you.

### ISSUE THREAD

**Issue by chaotan88** [codemirror/codemirror5#7093]
Can you provide the function of indenting lines in the code, just like vscode? Thank you.
![image](https://github.com/codemirror/codemirror5/assets/33088336/bc889316-5da2-49d0-94e4-c1aff78919ba)

**Comment by marijnh** [comment]
No. But the feature is called 'indent guides' and external implementations exist, like [this one](https://github.com/FlowerBirds/codemirror-addon-indent-guide).
