### ISSUE TITLE
Codemirror data overload and lagging problem

### ISSUE THREAD

**Issue by chenyajun-create** [codemirror/codemirror5#7094]
I am using the Codemirror version number is 5.44, and the React version is 16.13.1. There are about 200 lines of related code statements in the content area. When the code is only dozens of lines, it is not stuck. When the code is 200 lines, the deletion, addition, and modification statements are too laggy. The cursor will not come out until a few seconds later. What is the reason for this? I hope to get an answer!

**Comment by marijnh** [comment]
200 lines should be absolutely no problem, unless some of them are enormously long. There may be something else going on not related to the core library.

**Comment by chenyajun-create** [comment]
Thank you for your answer. I checked the code (written by someone else) and found that there is a chage event that executes every time, while the code in the change event is synchronous, blocking thread execution. Now, I have changed the change event to asynchronous and added 600ms of anti shake to solve this problem!

> 200 lines should be absolutely no problem, unless some of them are enormously long. There may be something else going on not related to the core library.

Thank you for your answer. I checked the code (written by someone else) and found that there is a chage event that executes every time, while the code in the change event is synchronous, blocking thread execution. Now, I have changed the change event to asynchronous and added 600ms of anti shake to solve this problem!

**Comment by chenyajun-create** [comment]
> 200 lines should be absolutely no problem, unless some of them are enormously long. There may be something else going on not related to the core library.

Thank you for your answer. I checked the code (written by someone else) and found that there is a chage event that executes every time, while the code in the change event is synchronous, blocking thread execution. Now, I have changed the change event to asynchronous and added 600ms of anti shake to solve this problem!
