### ISSUE TITLE
Set breakpoint to the left of line number

### ISSUE THREAD

**Issue by chen-xiaoxing** [codemirror/codemirror5#7096]
If both breakpoint and fold functions are set, will the breakpoint and fold buttons not overlap? How do I set the breakpoint to the left of the line number?

**Comment by marijnh** [comment]
The [`gutters` option](https://codemirror.net/5/doc/manual.html#option_gutters) controls the order of the gutters (by class name). Breakpoints and fold markers use different gutters, so there is room for both on the same line.

This is the bug tracker though. For questions, please use [the forum](https://discuss.codemirror.net).
