### ISSUE TITLE
vbscript language has no folding function

### ISSUE THREAD

**Issue by chen-xiaoxing** [codemirror/codemirror5#7097]
I can fold using javascript, but it fails when I switch to vbscript.The version number I use is 5.65.16, the vue version number is 3, and the node version is 14.This is my code：

<template>
    <el-drawer v-model="drawerVisable" title="" direction="rtl" size="100%">
        <template #default>
            <textarea id="editor" name="basic" ref="aceInputRef" />
        </template>
    </el-drawer>
</template>

<script setup lang="ts">
import { ref, nextTick, onMounted } from "vue";
// import { CodeMirror } from "codemirror/src/edit/main.js";
// import CodeMirror from "codemirror";
import CodeMirror from "codemirror/lib/codemirror.js";
import "codemirror/mode/vbscript/vbscript.js";
import "codemirror/mode/javascript/javascript.js";

import "codemirror/addon/fold/foldgutter.js";
import "codemirror/addon/fold/foldcode.js";
import "codemirror/addon/fold/brace-fold.js";

import 'codemirror/addon/hint/show-hint.css';
import 'codemirror/lib/codemirror.css';
import 'codemirror/addon/fold/foldgutter.css';

const drawerVisable = ref(true);
const aceInputRef = ref(null);

// 设置断点
const makeMarker = () => {
    var marker = document.createElement("div");
    marker.style.color = "#822";
    marker.style.lineHeight = "16px";
    marker.style.fontSize = "10px";
    marker.innerHTML = "●";
    return marker;
}
onMounted(() => {
    nextTick(() => {
        var editor = CodeMirror.fromTextArea(aceInputRef.value, {
            mode: "vbscript",
            lineNumbers: true,
            lineWrapping: true,
            extraKeys: { "Ctrl-Q": function (cm) { cm.foldCode(cm.getCursor()); } },
            foldGutter: true,
            gutters: ["breakpoints", "CodeMirror-linenumbers", "CodeMirror-foldgutter"]
        });

        editor.setValue(`Sub Main()
    Dim a As New M8Ball

    Do While True

        Dim q As String = ""
        Console.Write("ask me about the future... ")
        q = Console.ReadLine()

        If q.Trim <> "" Then
            Console.WriteLine("the answer is... {0}", a.getAnswer(q))
        Else
            Exit Do
        End If
    Loop

End Sub`)
        editor.foldCode(CodeMirror.Pos(13, 0));
        editor.on("gutterClick", function (cm, n, old) {
            var info = cm.lineInfo(n);
            cm.setGutterMarker(n, "breakpoints", info.gutterMarkers ? null : makeMarker());
        });
    })
})

</script>

<style>
.CodeMirror pre.CodeMirror-line,
.CodeMirror pre.CodeMirror-line-like {
    text-align: left;
}
</style>

**Comment by chen-xiaoxing** [comment]
> I can fold using javascript, but it fails when I switch to vbscript.The version number I use is 5.65.16, the vue version number is 3, and the node version is 14.This is my code：


The breakpoint flag cannot be set on the line with the fold flag.

**Comment by marijnh** [comment]
Indeed, there is no fold support for vbscript. This is unlikely to change at this point.
