### ISSUE TITLE
Wrong syntax highlighting for Groovy GStrings when interpolating values

### ISSUE THREAD

**Issue by FranzMartyn** [codemirror/codemirror5#7103]
I am coming from  [this codewars issue](https://github.com/codewars/runner/issues/318) , which uses codemirror 5 for it's editor.

Sometimes, codewars' editor gets the syntax highlighting for GStrings wrong when they contain interpolated values.

Codewars' editor does this:

![image](https://github.com/user-attachments/assets/15a40f6d-e659-4bb5-86a5-85dad46478d9)

instead of this (example from Intellij Idea):

![image](https://github.com/user-attachments/assets/18a04423-fee3-40dc-85a5-1e7689b6638f)

But the syntax highlighting on codewars' editor works when adding curly braces:

![image](https://github.com/user-attachments/assets/386c7882-fdb4-4592-bccc-d46080ea83e5)

**Comment by FranzMartyn** [comment]
It seems to display how it should when a character, that is neither a letter, nor a digit, nor whitespace, comes after the interpolated value

![image](https://github.com/user-attachments/assets/ab436622-f6ec-4763-9b60-e3927e334567)

**Comment by marijnh** [comment]
Attached patch should help.
