### ISSUE TITLE
Feature Request - multi selection

### ISSUE THREAD

**Issue by 0i0** [codemirror/codemirror5#778]
I know that this might be a big one to get your head around. but its totally worth it.

after i have moved to sublime text 2 for my development. its really hard going back to editors that don't have the multi select feature

it is a killer one and it saves tons of time

if you don't know what it is watch this movie first http://www.youtube.com/watch?v=i2SVJa2EGIw

it takes some time to get to use to the idea that your pointing power was multiplied many-folds. than you really start to invent new ways to work with this

WATCH OUT - if you'll get use to work with multi selection it will be very hard to go back

**Comment by gingersoulrecords** [comment]
I'm not sure if anyone said 'thanks' to @marijnh for doing this all these years ago. 

From someone who is benefiting from it now, thanks Marijn.
