### ISSUE TITLE
MaxLength attribute

### ISSUE THREAD

**Issue by nodesocket** [codemirror/codemirror5#821]
Is there a way to set a `MaxLength` number of characters allowed?

**Comment by guredd** [comment]
Better to use `cm.getDoc().lineSeparator()` instead of `\n`.

**Comment by promise96319** [comment]
But it cannot work when inputting Chinese. The beforeChange event does not return Chinese characters：

![image](https://github.com/codemirror/codemirror5/assets/38751863/55e72120-e693-4556-9108-0a6ac50b8dbe)
