### ISSUE TITLE
AutoFormat content after init

### ISSUE THREAD

**Issue by tomaswitek** [codemirror/codemirror5#841]
Hi,
is there a way, how to trigger auto formating after loading CodeMirror?
Thx

**Comment by vipcxj** [comment]
> Please use the mailing list for questions. This is not about a bug.
> 
> But yeah, of course there is. Just do what look http://codemirror.net/demo/formatting.html is doing, and do it after initializing the editor.

It seems that this demo is removed. so now how to format the whole content?

**Comment by marijnh** [comment]
CodeMirror dropped support for code formatting (it was too complicated to do and not really in scope for an editor package). You'll have to look for external libraries that can format or pretty-print the language you're interested in.

**Comment by vipcxj** [comment]
> CodeMirror dropped support for code formatting (it was too complicated to do and not really in scope for an editor package). You'll have to look for external libraries that can format or pretty-print the language you're interested in.

What a sad story
