### ISSUE TITLE
extra long word caused line wrap will break cursor movement

### ISSUE THREAD

**Issue by huangp** [codemirror/codemirror5#867]
Sample code snippet:

``` html
<div style="width:200px">
    <textarea id="code" name="code">
    javaCode {   
        stuff   
    }   
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    </textarea>
</div>

<script>
      var editor = CodeMirror.fromTextArea(document.getElementById("code"), 
        {
            lineNumbers: true,
            lineWrapping: true,
            mode: "htmlmixed"
        });
</script>
```

Description of the issue:
When there is an extra long word like "aaaaa..." in the sample, it will cause codemirror to break the word and wrap the line (it shows line number correctly). Move cursor to the beginning of that extra long word and press keyboard arrow right will NOT move cursor by one. Mouse click into the middle of the word is also not functioning. 

Note: if there are space in between then extra long "line" won't cause problem. Only happens when it can't wrap the line by words.

**Comment by xavadu** [comment]
I have exactly the same issue in the version 5.44.0

**Comment by CodePlayer** [comment]
Issue +1 in the version 5.48.0.
Place a very long single line of code in the editor.  E.g. paste a complete minimized js code into it.

At this point, the cursor display, cursor movement, and UI display all have serious problems.
